enum Disposal {
  GENERAL = "General Waste / Unknown",
  INCINERATION_MUNICIPAL = "Incineration (Municipal Waste)",
  INCINERATION_HAZARDOUS = "Incineration (Hazardous Waste)",
  LANDFILL = "Landfill",
  RECYCLING = "Recycling",
  COMPOSTING = "Composting",
}

const DisposalAverages = [
  {
    location: "United Arab Emirates",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Albania",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Armenia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Angola",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Argentina",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Austria",
    [Disposal.INCINERATION_MUNICIPAL]: 0.38,
    [Disposal.LANDFILL]: 0.24,
    [Disposal.RECYCLING]: 0.38,
  },
  {
    location: "Australia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Azerbaijan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Bosnia and Herzegovina",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Bangladesh",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Belgium",
    [Disposal.INCINERATION_MUNICIPAL]: 0.4,
    [Disposal.LANDFILL]: 0.2,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Bulgaria",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Bahrain",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Benin",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Brunei Darussalam",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Bolivia, Plurinational State of",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Brazil",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.58,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Botswana",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Belarus",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Canada",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Congo, DRC",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Congo",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Switzerland",
    [Disposal.INCINERATION_MUNICIPAL]: 0.5,
    [Disposal.LANDFILL]: 0.03,
    [Disposal.RECYCLING]: 0.47,
  },
  {
    location: "Cote d'Ivoire",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.85,
    [Disposal.RECYCLING]: 0.14,
  },
  {
    location: "Austria",
    [Disposal.INCINERATION_MUNICIPAL]: 0.38,
    [Disposal.LANDFILL]: 0.24,
    [Disposal.RECYCLING]: 0.38,
  },
  {
    location: "Australia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Belgium",
    [Disposal.INCINERATION_MUNICIPAL]: 0.4,
    [Disposal.LANDFILL]: 0.2,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Bulgaria",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Bahrain",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Brunei Darussalam",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Brazil",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.58,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Belarus",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Canada",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Switzerland",
    [Disposal.INCINERATION_MUNICIPAL]: 0.5,
    [Disposal.LANDFILL]: 0.03,
    [Disposal.RECYCLING]: 0.47,
  },
  {
    location: "Chile",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.28,
  },
  {
    location: "China",
    [Disposal.INCINERATION_MUNICIPAL]: 0.25,
    [Disposal.LANDFILL]: 0.45,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Colombia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.73,
    [Disposal.RECYCLING]: 0.25,
  },
  {
    location: "Costa Rica",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Cyprus",
    [Disposal.INCINERATION_MUNICIPAL]: 0.2,
    [Disposal.LANDFILL]: 0.55,
    [Disposal.RECYCLING]: 0.25,
  },
  {
    location: "Czechia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.3,
    [Disposal.LANDFILL]: 0.3,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Germany",
    [Disposal.INCINERATION_MUNICIPAL]: 0.38,
    [Disposal.LANDFILL]: 0.01,
    [Disposal.RECYCLING]: 0.61,
  },
  {
    location: "Denmark",
    [Disposal.INCINERATION_MUNICIPAL]: 0.54,
    [Disposal.LANDFILL]: 0.06,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Dominican Republic",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Algeria",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.19,
  },
  {
    location: "Ecuador",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Estonia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.4,
    [Disposal.LANDFILL]: 0.3,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Egypt",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.23,
  },
  {
    location: "Spain",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.5,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Finland",
    [Disposal.INCINERATION_MUNICIPAL]: 0.5,
    [Disposal.LANDFILL]: 0.1,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "France",
    [Disposal.INCINERATION_MUNICIPAL]: 0.35,
    [Disposal.LANDFILL]: 0.3,
    [Disposal.RECYCLING]: 0.35,
  },
  {
    location: "United Kingdom / Britain",
    [Disposal.INCINERATION_MUNICIPAL]: 0.42,
    [Disposal.LANDFILL]: 0.25,
    [Disposal.RECYCLING]: 0.33,
  },
  {
    location: "Greece",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.15,
  },
  {
    location: "Hong Kong",
    [Disposal.INCINERATION_MUNICIPAL]: 0.2,
    [Disposal.LANDFILL]: 0.53,
    [Disposal.RECYCLING]: 0.27,
  },
  {
    location: "Croatia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.1,
  },
  {
    location: "Haiti",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Hungary",
    [Disposal.INCINERATION_MUNICIPAL]: 0.15,
    [Disposal.LANDFILL]: 0.4,
    [Disposal.RECYCLING]: 0.45,
  },
  {
    location: "Indonesia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.25,
  },
  {
    location: "Ireland",
    [Disposal.INCINERATION_MUNICIPAL]: 0.38,
    [Disposal.LANDFILL]: 0.38,
    [Disposal.RECYCLING]: 0.24,
  },
  {
    location: "Israel",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.1,
  },
  {
    location: "India",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Iraq",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.19,
  },
  {
    location: "Iceland",
    [Disposal.INCINERATION_MUNICIPAL]: 0.5,
    [Disposal.LANDFILL]: 0.3,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Italy",
    [Disposal.INCINERATION_MUNICIPAL]: 0.25,
    [Disposal.LANDFILL]: 0.4,
    [Disposal.RECYCLING]: 0.35,
  },
  {
    location: "Jamaica",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Jordan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "Japan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.6,
    [Disposal.LANDFILL]: 0.1,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Kenya",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.23,
  },
  {
    location: "Kyrgyzstan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "Cambodia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Korea, DPRK",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Korea, Republic of",
    [Disposal.INCINERATION_MUNICIPAL]: 0.25,
    [Disposal.LANDFILL]: 0.3,
    [Disposal.RECYCLING]: 0.45,
  },
  {
    location: "Kuwait",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.24,
  },
  {
    location: "Kazakhstan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "Lebanon",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "Sri Lanka",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.23,
  },
  {
    location: "Lithuania",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Luxembourg",
    [Disposal.INCINERATION_MUNICIPAL]: 0.4,
    [Disposal.LANDFILL]: 0.1,
    [Disposal.RECYCLING]: 0.5,
  },
  {
    location: "Latvia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Libya",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Morocco",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.24,
  },
  {
    location: "Moldova, Republic of",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "Montenegro",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "North Macedonia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "Myanmar",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Mongolia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Malta",
    [Disposal.INCINERATION_MUNICIPAL]: 0.2,
    [Disposal.LANDFILL]: 0.5,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Mauritius",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Mexico",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.25,
  },
  {
    location: "Malaysia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Mozambique",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.24,
  },
  {
    location: "Namibia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Niger",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Nigeria",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.23,
  },
  {
    location: "Nicaragua",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Europe",
    [Disposal.INCINERATION_MUNICIPAL]: 0.25,
    [Disposal.LANDFILL]: 0.45,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Asia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.15,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.25,
  },
  {
    location: "Netherlands",
    [Disposal.INCINERATION_MUNICIPAL]: 0.35,
    [Disposal.LANDFILL]: 0.1,
    [Disposal.RECYCLING]: 0.55,
  },
  {
    location: "Norway",
    [Disposal.INCINERATION_MUNICIPAL]: 0.4,
    [Disposal.LANDFILL]: 0.1,
    [Disposal.RECYCLING]: 0.5,
  },
  {
    location: "Nepal",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "New Zealand",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Oman",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.24,
  },
  {
    location: "Panama",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Peru",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.23,
  },
  {
    location: "Philippines",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.25,
  },
  {
    location: "Pakistan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Poland",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Portugal",
    [Disposal.INCINERATION_MUNICIPAL]: 0.3,
    [Disposal.LANDFILL]: 0.4,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Paraguay",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Qatar",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Romania",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Serbia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.02,
    [Disposal.LANDFILL]: 0.8,
    [Disposal.RECYCLING]: 0.18,
  },
  {
    location: "Russia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Saudi Arabia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Sudan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Sweden",
    [Disposal.INCINERATION_MUNICIPAL]: 0.5,
    [Disposal.LANDFILL]: 0.1,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Singapore",
    [Disposal.INCINERATION_MUNICIPAL]: 0.4,
    [Disposal.LANDFILL]: 0.2,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Slovenia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.5,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Slovakia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.15,
    [Disposal.LANDFILL]: 0.55,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Senegal",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "South Sudan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "El Salvador",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Syrian Arab Republic",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Togo",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Thailand",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Tajikistan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Turkmenistan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Tunisia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Turkey",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Trinidad and Tobago",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Taiwan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.4,
    [Disposal.LANDFILL]: 0.2,
    [Disposal.RECYCLING]: 0.4,
  },
  {
    location: "Tanzania, United Republic Of",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Ukraine",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.75,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "United States",
    [Disposal.INCINERATION_MUNICIPAL]: 0.12,
    [Disposal.LANDFILL]: 0.53,
    [Disposal.RECYCLING]: 0.35,
  },
  {
    location: "Puerto Rico",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.2,
  },
  {
    location: "Uruguay",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.65,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Uzbekistan",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Venezuela",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Vietnam",
    [Disposal.INCINERATION_MUNICIPAL]: 0.1,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.3,
  },
  {
    location: "Kosovo",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Yemen",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "South Africa",
    [Disposal.INCINERATION_MUNICIPAL]: 0.05,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.25,
  },
  {
    location: "Zambia",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Zimbabwe",
    [Disposal.INCINERATION_MUNICIPAL]: 0.01,
    [Disposal.LANDFILL]: 0.7,
    [Disposal.RECYCLING]: 0.29,
  },
  {
    location: "Global",
    [Disposal.INCINERATION_MUNICIPAL]: 0.12,
    [Disposal.LANDFILL]: 0.6,
    [Disposal.RECYCLING]: 0.28,
  },
]

const DefaultDisposalAverage = {
  [Disposal.INCINERATION_MUNICIPAL]: 0.12,
  [Disposal.LANDFILL]: 0.6,
  [Disposal.RECYCLING]: 0.28,
} as { [key in Disposal]: number }

export default [
  {
    name: Disposal.GENERAL,
    factor_id: "",
  },
  {
    name: Disposal.INCINERATION_MUNICIPAL,
    factor_id: "6afd9bca-c005-4be2-8f7b-49d91acc1619",
  },
  {
    name: Disposal.INCINERATION_HAZARDOUS,
    factor_id: "0bd3c321-f6ea-4117-8823-5cf3a141f68d",
  },
  {
    name: Disposal.LANDFILL,
    factor_id: "0348c176-389b-4970-b0d1-0a0af655964b",
  },
  {
    name: Disposal.RECYCLING,
    factor_id: "031b7961-40b8-48d2-b2f1-766c843c5474",
  },
  {
    name: Disposal.COMPOSTING,
    factor_id: "a98dacf8-f472-405b-96b2-b4e2f62629dc",
  },
]

export { Disposal, DisposalAverages, DefaultDisposalAverage }
