const ecoinvent = [
  "1,1-difluoroethane, hfc-152a",
  "1,1-dimethylcyclopentane",
  "1-butanol",
  "1-methoxy-2-propanol",
  "1-methylcyclopropene",
  "1-naphthylacetic acid",
  "1-pentanol",
  "1-propanol",
  "2,3-dimethylbutan",
  "2,4-di-tert-butylphenol",
  "2,4-dichlorophenol",
  "2,4-dichlorotoluene",
  "2,4-dinitrotoluene",
  "2,5-dimethylhexane-2,5-dihydroperoxide",
  "2,6-di-tert-butylphenol",
  "2-butanol",
  "2-cyclopentone",
  "2-methyl-1-butanol",
  "2-methyl-2-butanol",
  "2-methylpentane",
  "2-nitroaniline",
  "2-pyridinol",
  "3-methyl-1-butanol",
  "3-methyl-1-butyl acetate",
  "3-methylpyridine",
  "4-methyl-2-pentanone",
  "4-tert-butylbenzaldehyde",
  "4-tert-butyltoluene",
  "6-benzyladenine",
  "C3 hydrocarbon mixture",
  "Dtpa, diethylenetriaminepentaacetic acid",
  "Edta, ethylenediaminetetraacetic acid",
  "H3po4 purification residue",
  "Mox fuel element, for light water reactor",
  "N,n-dimethylformamide",
  "N-methyl-2-pyrrolidone",
  "N2o retained, by regenerative thermal oxidation",
  "Nca hydroxide",
  "Nca oxide",
  "Nmc111 hydroxide",
  "Nmc111 oxide",
  "Nmc811 hydroxide",
  "Nmc811 oxide",
  "Nox retained, by selective catalytic reduction",
  "Sox retained, in hard coal flue gas desulfurisation",
  "Sox retained, in lignite flue gas desulfurisation",
  "Acetaldehyde",
  "Acetanilide",
  "Acetic acid, without water, in 98% solution state",
  "Acetic anhydride",
  "Acetoacetic acid",
  "Acetone cyanohydrin",
  "Acetone, liquid",
  "Acetonitrile",
  "Acetyl chloride",
  "Acetylene",
  "Acrolein",
  "Acrylic acid",
  "Acrylic binder, with water, in 54% solution state",
  "Acrylic dispersion, with water, in 58% solution state",
  "Acrylic filler",
  "Acrylic varnish, with water, in 53% solution state",
  "Acrylonitrile",
  "Acrylonitrile-butadiene-styrene copolymer",
  "Activated bentonite",
  "Activated carbon, granular",
  "Activated silica",
  "Adhesive mortar",
  "Adhesive, for metal",
  "Adipic acid",
  "Adiponitrile",
  "Alkyd paint, white, without solvent, in 60% solution state",
  "Alkyd paint, white, without water, in 60% solution state",
  "Alkyd resin, long oil, without solvent, in 70% white spirit solution state",
  "Alkyl sulphate (c12-14)",
  "Alkylbenzene sulfonate, linear, petrochemical",
  "Alkylbenzene, linear",
  "Alkylketene dimer sizing agent, for paper production",
  "Allyl chloride",
  "Alpha-naphthol",
  "Alpha-picoline",
  "Aluminium alloy, alli",
  "Aluminium alloy, almg3",
  "Aluminium alloy, metal matrix composite",
  "Aluminium chloride",
  "Aluminium collector foil, for li-ion battery",
  "Aluminium fluoride",
  "Aluminium hydroxide",
  "Aluminium in car shredder residue",
  "Aluminium oxide, metallurgical",
  "Aluminium oxide, non-metallurgical",
  "Aluminium removed by drilling, computer numerical controlled",
  "Aluminium removed by drilling, conventional",
  "Aluminium removed by milling, average",
  "Aluminium removed by milling, dressing",
  "Aluminium removed by milling, large parts",
  "Aluminium removed by milling, small parts",
  "Aluminium removed by turning, average, computer numerical controlled",
  "Aluminium removed by turning, average, conventional",
  "Aluminium removed by turning, primarily dressing, computer numerical controlled",
  "Aluminium removed by turning, primarily dressing, conventional",
  "Aluminium removed by turning, primarily roughing, computer numerical controlled",
  "Aluminium removed by turning, primarily roughing, conventional",
  "Aluminium scrap, new",
  "Aluminium scrap, post-consumer",
  "Aluminium scrap, post-consumer, prepared for melting",
  "Aluminium sulfate, powder",
  "Aluminium sulfate, without water, in 4.33% aluminium solution state",
  "Aluminium, cast alloy",
  "Aluminium, in mixed metal scrap",
  "Aluminium, primary, cast alloy slab from continuous casting",
  "Aluminium, primary, ingot",
  "Aluminium, primary, liquid",
  "Aluminium, wrought alloy",
  "Amidosulfuron",
  "Amine oxide",
  "Aminopyridine",
  "Ammonium chloride",
  "Ammonium nitrite",
  "Ammonium paratungstate",
  "Ammonium thiocyanate",
  "Anhydrite",
  "Anhydrite floor",
  "Anhydrite rock",
  "Anhydrite, burned",
  "Aniline",
  "Anionic resin",
  "Anode slime from electrorefining of copper, anode",
  "Anode, for metal electrolysis",
  "Anode, graphite, for li-ion battery",
  "Anode, paste, for aluminium electrolysis",
  "Anode, prebake, for aluminium electrolysis",
  "Anode, silicon coated graphite, for li-ion battery",
  "Anthranilic acid",
  "Anthraquinone",
  "Antimony",
  "Antimony slag, desulfurised",
  "Antimony slag, water-quenched",
  "Argon, crude, liquid",
  "Argon, liquid",
  "Arsine",
  "Asbestos, crysotile type",
  "Ascorbic acid",
  "Ash from deinking sludge",
  "Ash from paper production sludge",
  "Assembly of liquid crystal display, auxilliaries and energy use",
  "Autoclaved aerated concrete block",
  "Average incineration residue",
  "Azodicarbonamide",
  "Backlight, for liquid crystal display",
  "Bamboo culm",
  "Bamboo pole",
  "Barite",
  "Barium carbonate",
  "Barium hydroxide",
  "Barium oxide",
  "Barium sulfide",
  "Bark",
  "Bark chips, wet, measured as dry mass",
  "Basalt",
  "Base oil",
  "Base plaster",
  "Basic oxygen furnace dust",
  "Basic oxygen furnace dust, for recovery",
  "Basic oxygen furnace secondary metallurgy slag",
  "Basic oxygen furnace secondary metallurgy slag, for recovery",
  "Basic oxygen furnace slag",
  "Basic oxygen furnace slag, for recovery",
  "Basic oxygen furnace sludge",
  "Basic oxygen furnace sludge, for recovery",
  "Basic oxygen furnace waste",
  "Batch dyeing, fibre, cotton",
  "Battery cell, li-ion, lfp",
  "Battery cell, li-ion, limn2o4",
  "Battery cell, li-ion, nca",
  "Battery cell, li-ion, nmc111",
  "Battery cell, li-ion, nmc811",
  "Battery management system, for li-ion battery",
  "Battery module packaging, li-ion",
  "Battery separator",
  "Battery, li-ion, lfp, rechargeable, prismatic",
  "Battery, li-ion, limn2o4, rechargeable, prismatic",
  "Battery, li-ion, nca, rechargeable, prismatic",
  "Battery, li-ion, nmc111, rechargeable, prismatic",
  "Battery, li-ion, nmc811, rechargeable, prismatic",
  "Battery, nacl",
  "Battery, nimh, rechargeable, prismatic",
  "Battery, lead acid, rechargeable, stationary",
  "Bauxite",
  "Bentonite",
  "Benzal chloride",
  "Benzaldehyde",
  "Benzaldehyde-2-sulfonic acid",
  "Benzene",
  "Benzoic acid",
  "Benzyl alcohol",
  "Benzyl chloride",
  "Beryllium",
  "Beryllium hydroxide",
  "Bilge oil",
  "Biomethane, high pressure, vehicle grade",
  "Biomethane, low pressure, vehicle grade",
  "Biomethane, medium pressure, vehicle grade",
  "Biowaste",
  "Biowaste, garden waste",
  "Biowaste, kitchen and garden waste",
  "Bisphenol a epoxy based vinyl ester resin",
  "Bisphenol a, powder",
  "Bitumen adhesive compound, cold",
  "Bitumen adhesive compound, hot",
  "Bitumen seal",
  "Bitumen seal, alu80",
  "Bitumen seal, v60",
  "Bitumen seal, va4",
  "Bitumen seal, polymer ep4 flame retardant",
  "Blast furnace dust",
  "Blast furnace dust, for recovery",
  "Blast furnace slag",
  "Blast furnace sludge",
  "Blast furnace sludge, for recovery",
  "Blasting",
  "Bleaching and dyeing, yarn",
  "Bleaching, textile",
  "Blow moulding",
  "Borax, anhydrous, powder",
  "Boric acid, anhydrous, powder",
  "Boric oxide",
  "Boron carbide",
  "Boron trifluoride",
  "Bottom ash, mswi-wwt, ww from crt production",
  "Bottom ash, mswi-wwt, ww from ggbfs production",
  "Bottom ash, mswi-wwt, ww from lcd backlight production",
  "Bottom ash, mswi-wwt, ww from lcd production",
  "Bottom ash, mswi-wwt, ww from pv cell production",
  "Bottom ash, mswi-wwt, ww from ammonium paratungstate production",
  "Bottom ash, mswi-wwt, ww from black chrome coating",
  "Bottom ash, mswi-wwt, ww from ceramic production",
  "Bottom ash, mswi-wwt, ww from concrete production",
  "Bottom ash, mswi-wwt, ww from glass production",
  "Bottom ash, mswi-wwt, ww from grass refinery",
  "Bottom ash, mswi-wwt, ww from hard fibreboard production",
  "Bottom ash, mswi-wwt, ww from liquid crystal production",
  "Bottom ash, mswi-wwt, ww from maize starch production",
  "Bottom ash, mswi-wwt, ww from medium density board production",
  "Bottom ash, mswi-wwt, ww from particle board production",
  "Bottom ash, mswi-wwt, ww from pig iron production",
  "Bottom ash, mswi-wwt, ww from plywood production",
  "Bottom ash, mswi-wwt, ww from potato starch production",
  "Bottom ash, mswi-wwt, ww from soft fibreboard production",
  "Bottom ash, mswi-wwt, ww from tube collector production",
  "Bottom ash, mswi-wwt, ww from vegetable oil refinery",
  "Bottom ash, mswi-wwt, ww from wafer fabrication",
  "Bottom ash, mswi-wwt, ww, average",
  "Bottom ash, mswi-wwt, condensate from light oil boiler",
  "Bottom ash, mswi-wwt, heat carrier liquid, 40% c3h8o2",
  "Bottom ash, mswi-wwt, rainwater mineral oil storage",
  "Bottom ash, mswi-wwt[r], ww from anaerobic digestion of whey",
  "Bottom ash, mswi-wwt[u], ww from lorry production",
  "Bottom ash, mswi[f]-wwt, ww from crt production",
  "Bottom ash, mswi[f]-wwt, ww from lcd backlight production",
  "Bottom ash, mswi[f]-wwt, ww from lcd production",
  "Bottom ash, mswi[f]-wwt, ww from pv cell production",
  "Bottom ash, mswi[f]-wwt, ww from black chrome coating",
  "Bottom ash, mswi[f]-wwt, ww from ceramic production",
  "Bottom ash, mswi[f]-wwt, ww from concrete production",
  "Bottom ash, mswi[f]-wwt, ww from glass production",
  "Bottom ash, mswi[f]-wwt, ww from grass refinery",
  "Bottom ash, mswi[f]-wwt, ww from liquid crystal production",
  "Bottom ash, mswi[f]-wwt, ww from maize starch production",
  "Bottom ash, mswi[f]-wwt, ww from pig iron production",
  "Bottom ash, mswi[f]-wwt, ww from plywood production",
  "Bottom ash, mswi[f]-wwt, ww from potato starch production",
  "Bottom ash, mswi[f]-wwt, ww from soft fibreboard production",
  "Bottom ash, mswi[f]-wwt, ww from tube collector production",
  "Bottom ash, mswi[f]-wwt, ww from wafer fabrication",
  "Bottom ash, mswi[f]-wwt, ww, average",
  "Bottom ash, mswi[f]-wwt, condensate from light oil boiler",
  "Bottom ash, mswi[f]-wwt, heat carrier liquid, 40% c3h8o2",
  "Bottom ash, mswi[f]-wwt, rainwater mineral oil storage",
  "Bottom ash, mswi[f]-wwt[r], ww from anaerobic digestion of whey",
  "Bottom ash, mswi[f]-wwt[u], ww from lorry production",
  "Brake wear emissions, lorry",
  "Brake wear emissions, passenger car",
  "Brass",
  "Brass removed by drilling, computer numerical controlled",
  "Brass removed by drilling, conventional",
  "Brass removed by turning, average, computer numerical controlled",
  "Brass removed by turning, average, conventional",
  "Brass removed by turning, primarily dressing, computer numerical controlled",
  "Brass removed by turning, primarily dressing, conventional",
  "Brass removed by turning, primarily roughing, computer numerical controlled",
  "Brass removed by turning, primarily roughing, conventional",
  "Brazing solder, cadmium free",
  "Bromine",
  "Bromopropane",
  "Bromoxynil",
  "Bronze",
  "Bronze scrap, post-consumer",
  "Bulk lead-zinc concentrate",
  "Bundle, energy wood, measured as dry mass",
  "Burnt shale",
  "Butadiene",
  "Butane",
  "Butane-1,4-diol",
  "Butene, mixed",
  "Butyl acetate",
  "Butyl acrylate",
  "Butyldiglycol acetate",
  "Butyrolactone",
  "Cable, ribbon cable, 20-pin, with plugs",
  "Cable, unspecified",
  "Cadmium",
  "Cadmium chloride, semiconductor-grade",
  "Cadmium sludge from zinc electrolysis",
  "Cadmium sludge from zinc electrolysis stockpiling",
  "Cadmium sulfide, semiconductor-grade",
  "Cadmium telluride, semiconductor-grade",
  "Cadmium, semiconductor-grade",
  "Calcareous marl",
  "Calcined clay",
  "Calcium borates",
  "Calcium carbide, technical grade",
  "Calcium carbonate, precipitated",
  "Calcium chloride",
  "Calendering, rigid sheets",
  "Capacitor, auxilliaries and energy use",
  "Capacitor, electrolyte type, < 2cm height",
  "Capacitor, electrolyte type, > 2cm height",
  "Capacitor, film type, for through-hole mounting",
  "Capacitor, for surface-mounting",
  "Capacitor, tantalum-, for through-hole mounting",
  "Carbon black",
  "Carbon dioxide, in chemical industry",
  "Carbon dioxide, liquid",
  "Carbon disulfide",
  "Carbon fibre reinforced plastic, injection moulded",
  "Carbon monoxide",
  "Carbon tetrachloride",
  "Carboxymethyl cellulose, powder",
  "Carton board box production, with gravure printing",
  "Carton board box production, with offset printing",
  "Cast iron",
  "Cast iron removed by drilling, computer numerical controlled",
  "Cast iron removed by drilling, conventional",
  "Cast iron removed by milling, average",
  "Cast iron removed by milling, dressing",
  "Cast iron removed by milling, large parts",
  "Cast iron removed by milling, small parts",
  "Cast iron removed by turning, average, computer numerical controlled",
  "Cast iron removed by turning, average, conventional",
  "Cast iron removed by turning, primarily dressing, computer numerical controlled",
  "Cast iron removed by turning, primarily dressing, conventional",
  "Cast iron removed by turning, primarily roughing, computer numerical controlled",
  "Cast iron removed by turning, primarily roughing, conventional",
  "Casting, aluminium, lost-wax",
  "Casting, brass",
  "Casting, bronze",
  "Casting, steel, lost-wax",
  "Cathode, lfp, for li-ion battery",
  "Cathode, limn2o4, for li-ion battery",
  "Cathode, nca, for li-ion battery",
  "Cathode, nmc111, for li-ion battery",
  "Cathode, nmc811, for li-ion battery",
  "Cathode, for aluminium electrolysis",
  "Cathode-ray tube, cathode ray tube display",
  "Cationic resin",
  "Cellulose fibre",
  "Cement cast plaster floor",
  "Cement mortar",
  "Cement tile",
  "Cement, art",
  "Cement, cem ii/a",
  "Cement, cem ii/a-l",
  "Cement, cem ii/a-s",
  "Cement, cem ii/a-v",
  "Cement, cem ii/b",
  "Cement, cem ii/b-l",
  "Cement, cem ii/b-s",
  "Cement, cem ii/b-v",
  "Cement, cem iii/a",
  "Cement, cem iii/b",
  "Cement, cem iii/c",
  "Cement, cem iv/a",
  "Cement, cem iv/b",
  "Cement, cem v/a",
  "Cement, cem v/b",
  "Cement, cp ii-e",
  "Cement, cp ii-f",
  "Cement, cp ii-z",
  "Cement, cp iii",
  "Cement, cp iv",
  "Cement, cp v rs",
  "Cement, portland",
  "Cement, portland slag",
  "Cement, pozzolana portland",
  "Cement, zn/d, new alternative constituents 36-50%, in conformity with sia 2049",
  "Cement, type i (sm)",
  "Cement, type i-pm",
  "Cement, type ico",
  "Cement, type ip",
  "Cement, type ip/p",
  "Cement, type is",
  "Cement, type s",
  "Cement, type general use",
  "Cement, unspecified",
  "Ceramic tile",
  "Cerium oxide",
  "Charcoal",
  "Charger, electric passenger car",
  "Charger, for electric scooter",
  "Chassis, internet access equipment",
  "Chemi-thermomechanical pulp",
  "Chemical factory",
  "Chemical, inorganic",
  "Chemical, organic",
  "Chloridazon",
  "Chlorine dioxide",
  "Chlorine, for reuse in titanium tetrachloride production",
  "Chlorine, for reuse in zirconium and hafnium tetrachloride production",
  "Chlorine, gaseous",
  "Chlorine, liquid",
  "Chlormequat chloride",
  "Chloroacetic acid",
  "Chloroacetyl chloride",
  "Chlorodifluoromethane",
  "Chloromethyl methyl ether",
  "Chloronitrobenzene",
  "Chloropropionic acid",
  "Chlorosulfonic acid",
  "Chlorpropham",
  "Chromite ore concentrate",
  "Chromium",
  "Chromium oxide, flakes",
  "Chromium steel pipe",
  "Chromium steel removed by drilling, computer numerical controlled",
  "Chromium steel removed by drilling, conventional",
  "Chromium steel removed by milling, average",
  "Chromium steel removed by milling, dressing",
  "Chromium steel removed by milling, large parts",
  "Chromium steel removed by milling, small parts",
  "Chromium steel removed by turning, average, computer numerical controlled",
  "Chromium steel removed by turning, average, conventional",
  "Chromium steel removed by turning, primarily dressing, computer numerical controlled",
  "Chromium steel removed by turning, primarily dressing, conventional",
  "Chromium steel removed by turning, primarily roughing, computer numerical controlled",
  "Chromium steel removed by turning, primarily roughing, conventional",
  "Citric acid",
  "Clay",
  "Clay brick",
  "Clay plaster",
  "Cleaning consumables, without water, in 13.6% solution state",
  "Cleft timber, measured as dry mass",
  "Clinker",
  "Coal slurry",
  "Coal tar",
  "Coating from waste cathode ray tube display",
  "Coating powder",
  "Cobalt",
  "Cobalt acetate",
  "Cobalt carbonate",
  "Cobalt hydroxide",
  "Cobalt oxide",
  "Cobalt sulfate",
  "Cobwork",
  "Cocamide diethanolamine",
  "Compost",
  "Concrete block",
  "Concrete roof tile",
  "Containerboard, fluting medium",
  "Containerboard, linerboard",
  "Containerboard, unspecified",
  "Continuous dyeing, fibre, cotton",
  "Contouring, brass",
  "Contouring, bronze",
  "Controller, for electric scooter",
  "Converter, for electric passenger car",
  "Copper cake",
  "Copper carbonate",
  "Copper collector foil, for li-ion battery",
  "Copper concentrate, sulfide ore",
  "Copper in car shredder residue",
  "Copper oxide",
  "Copper scrap, sorted, pressed",
  "Copper slag",
  "Copper sulfate",
  "Copper telluride cement",
  "Copper, anode",
  "Copper, cathode",
  "Copper-rich materials",
  "Core board",
  "Cork slab",
  "Cork, raw",
  "Corrugated board box",
  "Cover plaster, mineral",
  "Cover plaster, organic",
  "Crust from parkes process for lead production",
  "Cryolite",
  "Cumene",
  "Cyanoacetic acid",
  "Cyanogen chloride",
  "Cyanuric chloride",
  "Cyclohexane",
  "Cyclohexanol",
  "Cyclohexanone",
  "Daminozide",
  "De-icer",
  "Decabromodiphenyl ether",
  "Decarbonising waste",
  "Decommissioned chemical production facilities",
  "Decommissioned pipeline, natural gas",
  "Deep drawing, steel, 10000 kn press, automode",
  "Deep drawing, steel, 10000 kn press, single stroke",
  "Deep drawing, steel, 3500 kn press, automode",
  "Deep drawing, steel, 3500 kn press, single stroke",
  "Deep drawing, steel, 38000 kn press, automode",
  "Deep drawing, steel, 38000 kn press, single stroke",
  "Deep drawing, steel, 650 kn press, automode",
  "Deep drawing, steel, 650 kn press, single stroke",
  "Deinked pulp, wet lap",
  "Deinking emulsion, in paper production",
  "Diborane",
  "Dichlobenil",
  "Dichloromethane",
  "Dichloropropene",
  "Dicyclopentadiene based unsaturated polyester resin",
  "Diesel",
  "Diesel, low-sulfur",
  "Diethanolamine",
  "Diethyl ether, without water, in 99.95% solution state",
  "Diethylene glycol",
  "Digester sludge",
  "Dimethyl carbonate",
  "Dimethyl ether",
  "Dimethyl hexanediol",
  "Dimethyl hexynediol",
  "Dimethyl malonate",
  "Dimethyl sulfate",
  "Dimethyl sulfide",
  "Dimethyl sulfoxide",
  "Dimethylacetamide",
  "Dimethylamine",
  "Dimethylamine borane",
  "Dimethylaminopropylamine",
  "Dimethyldichlorosilane",
  "Dinitrogen tetroxide",
  "Dioctyl adipate",
  "Dioctyl terephthalate",
  "Diode, auxilliaries and energy use",
  "Diode, glass-, for surface-mounting",
  "Diode, glass-, for through-hole mounting",
  "Dioxane",
  "Dipropyl amine",
  "Dipropylene glycol monomethyl ether",
  "Disodium disulphite",
  "Dodecanol",
  "Dolomite",
  "Drawing of pipe, steel",
  "Drilling waste",
  "Dross from al electrolysis",
  "Dysprosium oxide",
  "Electric arc furnace dust",
  "Electric arc furnace secondary metallurgy slag",
  "Electric arc furnace secondary metallurgy slag, for recovery",
  "Electric arc furnace slag",
  "Electric arc furnace slag, for recovery",
  "Electric connector, peripheral component interconnect buss",
  "Electric connector, peripheral type buss",
  "Electric connector, wire clamp",
  "Electric motor, electric passenger car",
  "Electric motor, for electric scooter",
  "Electric motor, vehicle",
  "Electric scooter, without battery",
  "Electrode, negative, lic6",
  "Electrode, negative, ni",
  "Electrode, positive, lani5",
  "Electrolyte, koh, lioh additive",
  "Electrolyte, copper-rich",
  "Electrolyte, for li-ion battery",
  "Electrolyte, for solid oxide fuel cell",
  "Electron gun, for cathode ray tube display",
  "Electronic component, active, unspecified",
  "Electronic component, passive, mobile, earpiece and speaker",
  "Electronic component, passive, unspecified",
  "Electronics scrap",
  "Electronics scrap from control units",
  "Electronics, for control units",
  "Electrostatic paint",
  "Energy and auxilliary inputs, metal working factory",
  "Energy and auxilliary inputs, metal working machine",
  "Enriched uranium, 4.2%",
  "Enzymes",
  "Epichlorohydrin",
  "Epoxy resin insulator, al2o3",
  "Epoxy resin insulator, sio2",
  "Epoxy resin, liquid",
  "Erbium oxide",
  "Esterquat",
  "Esters of versatic acid",
  "Ethane",
  "Ethanol, without water, in 95% solution state, from fermentation",
  "Ethanol, without water, in 99.7% solution state, from ethylene",
  "Ethanol, without water, in 99.7% solution state, from fermentation",
  "Ethanol, without water, in 99.7% solution state, from fermentation, vehicle grade",
  "Ethephon",
  "Ethoxylated alcohol (ae11)",
  "Ethoxylated alcohol (ae3)",
  "Ethoxylated alcohol (ae7)",
  "Ethoxylated alcohol (ae>20)",
  "Ethyl acetate",
  "Ethyl benzene",
  "Ethyl tert-butyl ether",
  "Ethylamine",
  "Ethylene",
  "Ethylene bromide",
  "Ethylene carbonate",
  "Ethylene dichloride",
  "Ethylene glycol",
  "Ethylene glycol diethyl ether",
  "Ethylene glycol dimethyl ether",
  "Ethylene glycol monoethyl ether",
  "Ethylene oxide",
  "Ethylene vinyl acetate copolymer",
  "Ethylene, pipeline system",
  "Ethylenediamine",
  "Ethylvinylacetate, foil",
  "Europium oxide",
  "Expanded clay",
  "Expanded perlite",
  "Expanded vermiculite",
  "Explosive, tovex",
  "Extrusion of plastic sheets and thermoforming, inline",
  "Extrusion, co-extrusion",
  "Extrusion, plastic film",
  "Extrusion, plastic pipes",
  "Fan, for power supply unit, desktop computer",
  "Fatty acid",
  "Fatty acid methyl ester",
  "Fatty alcohol",
  "Fatty alcohol sulfate",
  "Feldspar",
  "Ferrite",
  "Ferrochromium, high-carbon, 55% cr",
  "Ferrochromium, high-carbon, 68% cr",
  "Ferromanganese, high-coal, 74.5% mn",
  "Ferronickel",
  "Ferroniobium, 66% nb",
  "Ferrosilicon",
  "Ferrous metal, in mixed metal scrap",
  "Fibre and fabric waste, polyester",
  "Fibre cement corrugated slab",
  "Fibre cement facing tile",
  "Fibre cement facing tile, large format",
  "Fibre cement facing tile, small format",
  "Fibre cement roof slate",
  "Fibre, polyester",
  "Fibre, silk, short",
  "Fibre, viscose",
  "Filter dust from al electrolysis",
  "Finishing, textile, knit cotton",
  "Finishing, textile, woven cotton",
  "Flat glass, coated",
  "Flat glass, uncoated",
  "Flattened bamboo",
  "Fleece, polyethylene",
  "Fluazifop-butyl",
  "Fluorescent whitening agent, das1, triazinylaminostilben type",
  "Fluorescent whitening agent, distyrylbiphenyl type",
  "Fluorine, liquid",
  "Fluorspar, 97% purity",
  "Fluosilicic acid, without water, in 22% solution state",
  "Flux, for wave soldering",
  "Fly ash and scrubber sludge",
  "Flyash brick",
  "Foam glass",
  "Foam glass, electricity from renewable energy products",
  "Foaming agent",
  "Folding boxboard carton",
  "Forging, steel",
  "Formaldehyde",
  "Formic acid",
  "Fraction 1 from naphtha separation",
  "Fraction 7 from naphtha separation",
  "Fraction 8 from naphtha separation",
  "Frit, for cathode ray tube display",
  "Frit, for ceramic tile",
  "Funnel glass, for cathode ray tube display",
  "Furniture, wooden",
  "Gadolinium oxide",
  "Gallium, in bayer liquor from aluminium production",
  "Gallium, semiconductor-grade",
  "Glass cullet, for saint-gobain isover sa",
  "Glass cullet, from fluorescent lamps treatment",
  "Glass cullet, from used cathode ray tube panels",
  "Glass cullet, lead containing, from used cathode ray tube",
  "Glass cullet, mixed glass from used cathode ray tube",
  "Glass cullet, sorted",
  "Glass fibre",
  "Glass fibre reinforced plastic, polyamide, injection moulded",
  "Glass fibre reinforced plastic, polyester resin, hand lay-up",
  "Glass from used cathode ray tube",
  "Glass tube, borosilicate",
  "Glass wool mat",
  "Glass wool mat, uncoated, saint-gobain isover sa",
  "Glass, for liquid crystal display",
  "Glider, for electric scooter",
  "Glider, passenger car",
  "Glucose",
  "Glycerine",
  "Glycine",
  "Glyoxal",
  "Gold",
  "Gold, unrefined",
  "Gold-silver, ingot",
  "Granulated blast furnace slag",
  "Graphic paper, 100% recycled",
  "Graphite",
  "Graphite, battery grade",
  "Gravel, crushed",
  "Gravel, round",
  "Green liquor dregs",
  "Ground granulated blast furnace slag",
  "Gypsum fibreboard",
  "Gypsum plasterboard",
  "Gypsum, mineral",
  "Hafnium sponge",
  "Hafnium tetrachloride",
  "Hard coal",
  "Hard coal ash",
  "Hard coal, run-of-mine",
  "Hazardous waste, for incineration",
  "Hazardous waste, for underground deposit",
  "Heavy fuel oil",
  "Heavy water",
  "Helium",
  "Helium, crude",
  "Helium, crude stockpiling",
  "Heptane",
  "Hexafluoroethane",
  "Hexamethyldisilazane",
  "Hexamethylene-1,6-diisoncyanate",
  "Hexamethylenediamine",
  "Hexane",
  "High voltage system, for li-ion battery",
  "Holmium oxide",
  "Hot rolling, steel",
  "Hydrazine",
  "Hydrazine sulfate",
  "Hydrochloric acid, without water, in 30% solution state",
  "Hydrogen cyanide",
  "Hydrogen fluoride",
  "Hydrogen peroxide, without water, in 50% solution state",
  "Hydrogen sulfide",
  "Hydrogen, gaseous",
  "Hydrogen, liquid",
  "Hydroquinone",
  "Hydroxylamine",
  "Ilmenite, 54% titanium dioxide",
  "Imidazole",
  "Impact extrusion of aluminium, 1 stroke",
  "Impact extrusion of aluminium, 2 strokes",
  "Impact extrusion of aluminium, 3 strokes",
  "Impact extrusion of aluminium, 4 strokes",
  "Impact extrusion of aluminium, 5 strokes",
  "Impact extrusion of aluminium, cold, initial surface treatment",
  "Impact extrusion of aluminium, cold, tempering",
  "Impact extrusion of aluminium, deformation stroke",
  "Impact extrusion of steel, cold, 1 strokes",
  "Impact extrusion of steel, cold, 2 strokes",
  "Impact extrusion of steel, cold, 3 strokes",
  "Impact extrusion of steel, cold, 4 strokes",
  "Impact extrusion of steel, cold, 5 strokes",
  "Impact extrusion of steel, cold, deformation stroke",
  "Impact extrusion of steel, cold, initial surface treatment",
  "Impact extrusion of steel, cold, tempering",
  "Impact extrusion of steel, hot, 1 strokes",
  "Impact extrusion of steel, hot, 2 strokes",
  "Impact extrusion of steel, hot, 3 strokes",
  "Impact extrusion of steel, hot, 4 strokes",
  "Impact extrusion of steel, hot, 5 strokes",
  "Impact extrusion of steel, hot, deformation stroke",
  "Impact extrusion of steel, hot, initial warming",
  "Impact extrusion of steel, hot, tempering",
  "Impact extrusion of steel, warm, 1 strokes",
  "Impact extrusion of steel, warm, 2 strokes",
  "Impact extrusion of steel, warm, 3 strokes",
  "Impact extrusion of steel, warm, 4 strokes",
  "Impact extrusion of steel, warm, 5 strokes",
  "Impact extrusion of steel, warm, deformation stroke",
  "Impact extrusion of steel, warm, initial warming",
  "Indium",
  "Indium rich leaching residues, from zinc production",
  "Indium rich leaching residues, from zinc production stockpiling",
  "Indium tin oxide powder, nanoscale, for sputtering target",
  "Indolylbutyric acid",
  "Inductor, auxilliaries and energy use",
  "Inductor, low value multilayer chip",
  "Inductor, miniature radio frequency chip",
  "Inductor, ring core choke type",
  "Industrial machine, heavy, unspecified",
  "Inert filler",
  "Inert gas for discharge lamps",
  "Inert waste",
  "Inert waste, for final disposal",
  "Injection moulding",
  "Insulated gate bipolar transistor, electric vehicle application",
  "Integrated battery interface system, for li-ion battery",
  "Integrated circuit, logic type",
  "Integrated circuit, memory type",
  "Internal combustion engine, passenger car",
  "Inverter, for electric passenger car",
  "Iodine",
  "Ioxynil",
  "Iron ore concentrate",
  "Iron ore, crude ore, 46% fe",
  "Iron ore, crude ore, 63% fe",
  "Iron pellet",
  "Iron scrap, sorted, pressed",
  "Iron scrap, unsorted",
  "Iron sinter",
  "Iron sulfate",
  "Iron(ii) chloride",
  "Iron(iii) chloride, without water, in 14% iron solution state",
  "Iron (iii) chloride, without water, in 40% solution state",
  "Iron(iii) chloride, without water, in a 12% iron solution state",
  "Iron(iii) sulfate, without water, in 12.5% iron solution state",
  "Iron-nickel-chromium alloy",
  "Isobutane",
  "Isobutanol",
  "Isobutyl acetate",
  "Isohexane",
  "Isophorondiisocyante",
  "Isophthalic acid based unsaturated polyester resin",
  "Isopropanol",
  "Isopropyl acetate",
  "Isopropylamine",
  "Kaolin",
  "Kerosene",
  "Kraft paper",
  "Krypton, gaseous",
  "Lactic acid",
  "Land tenure, arable land, measured as carbon net primary productivity, annual crop",
  "Land tenure, arable land, measured as carbon net primary productivity, forest, intensive",
  "Land tenure, arable land, measured as carbon net primary productivity, pasture, man made",
  "Land tenure, arable land, measured as carbon net primary productivity, perennial crop",
  "Lanthanum oxide",
  "Lanthanum-cerium oxide",
  "Laterite, mineral",
  "Latex",
  "Lauric diethanolamide",
  "Layered sodium silicate, sks-6, powder",
  "Leach residue from copper production",
  "Lead",
  "Lead concentrate",
  "Lead concentrate stockpiling",
  "Lead in car shredder residue",
  "Lead smelter slag",
  "Light clay brick",
  "Light emitting diode",
  "Light fuel oil",
  "Light mortar",
  "Lightweight concrete block, expanded clay",
  "Lightweight concrete block, expanded perlite",
  "Lightweight concrete block, expanded vermiculite",
  "Lightweight concrete block, polystyrene",
  "Lightweight concrete block, pumice",
  "Lignite",
  "Lignite ash",
  "Lime",
  "Lime mortar",
  "Lime, hydrated, loose weight",
  "Lime, hydrated, packed",
  "Lime, hydraulic",
  "Lime, packed",
  "Limestone residue",
  "Limestone, crushed, for mill",
  "Limestone, crushed, washed",
  "Limestone, unprocessed",
  "Liquefied petroleum gas",
  "Liquid crystal display, minor components, auxilliaries and assembly effort",
  "Liquid crystal display, unmounted",
  "Liquid crystal display, unmounted, mobile device",
  "Liquid packaging board",
  "Liquid packaging board container",
  "Lithium",
  "Lithium brine, 6.7 % li",
  "Lithium carbonate",
  "Lithium chloride",
  "Lithium fluoride",
  "Lithium hexafluorophosphate",
  "Lithium hydroxide",
  "Lithium iron phosphate",
  "Lithium manganese oxide",
  "Lithium sulfate",
  "Low voltage system, for li-ion battery",
  "Lubricating oil",
  "Lutetium oxide",
  "Magnesium",
  "Magnesium chloride, from hafnium sponge production",
  "Magnesium chloride, from titanium sponge production",
  "Magnesium chloride, from zirconium sponge production",
  "Magnesium oxide",
  "Magnesium sulfate",
  "Magnesium, for reuse in hafnium sponge production",
  "Magnesium, for reuse in titanium sponge production",
  "Magnesium, for reuse in zirconium sponge production",
  "Magnesium-alloy, az91",
  "Magnesium-alloy, az91, diecast",
  "Magnetite",
  "Maleic anhydride",
  "Maleic hydrazide",
  "Maleic unsaturated polyester resin",
  "Malusil",
  "Maneb",
  "Manganese",
  "Manganese concentrate",
  "Manganese dioxide",
  "Manganese sulfate",
  "Manganese(iii) oxide",
  "Mastic asphalt",
  "Melamine",
  "Melamine formaldehyde resin",
  "Melamine urea formaldehyde adhesive",
  "Mepiquat chloride",
  "Mercerizing, textile",
  "Mercury",
  "Metal catalyst for catalytic converter",
  "Metal part of electronics scrap, in copper, anode",
  "Metal working machine, unspecified",
  "Metal working, average for aluminium product manufacturing",
  "Metal working, average for chromium steel product manufacturing",
  "Metal working, average for copper product manufacturing",
  "Metal working, average for metal product manufacturing",
  "Metal working, average for steel product manufacturing",
  "Metalliferous hydroxide sludge",
  "Metallization paste, back side",
  "Metallization paste, back side, aluminium",
  "Metallization paste, front side",
  "Metazachlor",
  "Methacrylic acid",
  "Methallylchloride",
  "Methane sulfonic acid",
  "Methanol",
  "Methanol, from biomass",
  "Methyl acetate",
  "Methyl acrylate",
  "Methyl ethyl ketone",
  "Methyl formate",
  "Methyl iodide",
  "Methyl methacrylate",
  "Methyl tert-butyl ether",
  "Methyl-3-methoxypropionate",
  "Methylamine",
  "Methylchloride",
  "Methylcyclohexane",
  "Methylcyclopentane",
  "Methylene diphenyl diisocyanate",
  "Mill scale",
  "Mischmetal",
  "Molybdenite",
  "Molybdenum",
  "Molybdenum trioxide",
  "Monochlorobenzene",
  "Monochloropentafluoroethane",
  "Monoethanolamine",
  "Morpholine",
  "Municipal solid waste",
  "N-olefins",
  "Naphtha",
  "Naphthalene sulfonic acid",
  "Natural gas liquids",
  "Natural gas, high pressure, vehicle grade",
  "Natural gas, low pressure, vehicle grade",
  "Natural gas, medium pressure, vehicle grade",
  "Natural stone plate, cut",
  "Natural stone plate, grounded",
  "Natural stone plate, polished",
  "Neodymium oxide",
  "Neutralising agent, sodium hydroxide-equivalent",
  "Nickel concentrate, 16% ni",
  "Nickel concentrate, 7% ni",
  "Nickel smelter slag",
  "Nickel sulfate",
  "Nickel, class 1",
  "Nickel-rich materials",
  "Nitrate salts, for solar power application",
  "Nitric oxide",
  "Nitrobenzene",
  "Nitrogen, liquid",
  "Nitrous dioxide",
  "Nitrous oxide",
  "Non-fe-co-metals, from li-ion battery, hydrometallurgical processing",
  "Non-fe-co-metals, from used li-ion battery, pyrometallurgical processing",
  "Non-ionic surfactant",
  "Non-sulfidic overburden, off-site",
  "Non-sulfidic tailing, off-site",
  "Nuclear fuel element, for boiling water reactor, uo2 4.0% & mox",
  "Nuclear fuel element, for pressure water reactor, uo2 3.8% & mox",
  "Nuclear fuel element, for pressure water reactor, uo2 3.9% & mox",
  "Nuclear fuel element, for pressure water reactor, uo2 4.0% & mox",
  "Nuclear fuel element, for pressure water reactor, uo2 4.2% & mox",
  "Nuclear fuel element, for pressure water reactor, uo2 4.2% centrifuge & mox",
  "Nylon 6",
  "Nylon 6, glass-filled",
  "Nylon 6-6",
  "Nylon 6-6, glass-filled",
  "O-aminophenol",
  "O-chlorobenzaldehyde",
  "O-chlorotoluene",
  "O-cresol",
  "O-dichlorobenzene",
  "O-nitrophenol",
  "Octabenzone",
  "Optical brighteners, for paper production",
  "Ortho-phenylene diamine",
  "Orthophthalic acid based unsaturated polyester resin",
  "Oxalic acid",
  "Oxygen, liquid",
  "Ozone, liquid",
  "P-chlorophenol",
  "P-dichlorobenzene",
  "P-nitrophenol",
  "P-nitrotoluene",
  "Packaging film, low density polyethylene",
  "Packaging glass, brown",
  "Packaging glass, green",
  "Packaging glass, white",
  "Packaging, for fertilisers",
  "Packaging, for fertilisers or pesticides",
  "Packaging, for pesticides",
  "Packing, cement",
  "Packing, clay product",
  "Packing, fibre cement product",
  "Packing, lime product",
  "Paclobutrazol",
  "Palladium",
  "Panel glass, for cathode ray tube display",
  "Paper sack",
  "Paper, melamine impregnated",
  "Paper, newsprint",
  "Paper, woodcontaining, lightweight coated",
  "Paper, woodcontaining, supercalendered",
  "Paper, woodfree, coated",
  "Paper, woodfree, uncoated",
  "Para-phenylene diamine",
  "Paraffin",
  "Passenger car, diesel",
  "Passenger car, electric, without battery",
  "Passenger car, petrol/natural gas",
  "Peat",
  "Pentaerythritol",
  "Pentane",
  "Perfluoropentane",
  "Perlite",
  "Permanent magnet, for electric motor",
  "Petrol, 15% etbe additive by volume, with ethanol from biomass",
  "Petrol, 4% etbe additive by volume, with ethanol from biomass",
  "Petrol, 5% ethanol by volume from biomass",
  "Petrol, low-sulfur",
  "Petrol, two-stroke blend",
  "Petrol, unleaded",
  "Petroleum",
  "Petroleum coke",
  "Petroleum combustion, in drilling tests",
  "Petroleum slack wax",
  "Phenol",
  "Phenolic resin",
  "Phenyl acetic acid",
  "Phenyl isocyanate",
  "Phosgene, liquid",
  "Phosphoric acid, industrial grade, without water, in 85% solution state",
  "Phosphorous chloride",
  "Phosphorus oxychloride",
  "Phosphorus pentachloride",
  "Phosphorus trichloride",
  "Phosphorus, white, liquid",
  "Phthalic anhydride",
  "Phthalimide",
  "Pig iron",
  "Piperidine",
  "Pitch",
  "Pitch despergents, in paper production",
  "Plaster mixing",
  "Plastic flake, consumer electronics, for recycling",
  "Plastic granulate, unspecified, recycled",
  "Plasticiser, for concrete, based on sulfonated melamine formaldehyde",
  "Platinum",
  "Platinum group metal concentrate",
  "Polar fleece, energy use only",
  "Polarizer, liquid crystals and colour filters, for liquid crystal display",
  "Pollutant from rail ballast",
  "Polyacrylamide",
  "Polyaluminium chloride",
  "Polybutadiene",
  "Polycarbonate",
  "Polycarboxylates, 40% active substance",
  "Polydimethylsiloxane",
  "Polyester resin, unsaturated",
  "Polyester-complexed starch biopolymer",
  "Polyethylene terephthalate, granulate, amorphous",
  "Polyethylene terephthalate, granulate, amorphous, recycled",
  "Polyethylene terephthalate, granulate, bottle grade",
  "Polyethylene terephthalate, granulate, bottle grade, recycled",
  "Polyethylene, high density, granulate",
  "Polyethylene, high density, granulate, recycled",
  "Polyethylene, linear low density, granulate",
  "Polyethylene, low density, granulate",
  "Polylactide, granulate",
  "Polymer foaming",
  "Polymethyl methacrylate, beads",
  "Polymethyl methacrylate, sheet",
  "Polyol",
  "Polyphenylene sulfide",
  "Polypropylene, granulate",
  "Polystyrene foam slab",
  "Polystyrene foam slab for perimeter insulation",
  "Polystyrene foam slab with graphite, 6% recycled",
  "Polystyrene foam slab, 10% recycled",
  "Polystyrene scrap, post-consumer",
  "Polystyrene, expandable",
  "Polystyrene, extruded",
  "Polystyrene, general purpose",
  "Polystyrene, high impact",
  "Polysulfide, sealing compound",
  "Polysulfone",
  "Polyurethane adhesive",
  "Polyurethane, flexible foam",
  "Polyurethane, flexible foam, flame retardant",
  "Polyurethane, rigid foam",
  "Polyvinylchloride, bulk polymerised",
  "Polyvinylchloride, emulsion polymerised",
  "Polyvinylchloride, suspension polymerised",
  "Polyvinylfluoride",
  "Polyvinylfluoride, dispersion",
  "Polyvinylfluoride, film",
  "Polyvinylidenchloride, granulate",
  "Portachrom",
  "Portafer",
  "Potassium carbonate",
  "Potassium hydroxide",
  "Potassium nitrate, industrial grade",
  "Potassium nitrate, technical grade",
  "Potassium perchlorate",
  "Potassium permanganate",
  "Potentiometer, unspecified",
  "Power distribution unit, for electric passenger car",
  "Powertrain, for electric passenger car",
  "Powertrain, for electric scooter",
  "Praseodymium oxide",
  "Praseodymium-neodymium oxide",
  "Precious metal from electronics scrap, in anode slime",
  "Printed paper",
  "Printed paper, offset",
  "Printed wiring board, for power supply unit, desktop computer, pb containing",
  "Printed wiring board, for power supply unit, desktop computer, pb free",
  "Printed wiring board, mounted mainboard, desktop computer, pb containing",
  "Printed wiring board, mounted mainboard, desktop computer, pb free",
  "Printed wiring board, mounted mainboard, laptop computer, pb containing",
  "Printed wiring board, mounted mainboard, laptop computer, pb free",
  "Printed wiring board, surface mounted, unspecified, pb containing",
  "Printed wiring board, surface mounted, unspecified, pb free",
  "Printed wiring board, through-hole mounted, unspecified, pb containing",
  "Printed wiring board, through-hole mounted, unspecified, pb free",
  "Printing ink, offset, without solvent, in 47.5% solution state",
  "Printing ink, rotogravure, without solvent, in 55% toluene solution state",
  "Process-specific burdens, hazardous waste incineration plant",
  "Process-specific burdens, import of copper to switzerland",
  "Process-specific burdens, inert material landfill",
  "Process-specific burdens, municipal waste incineration",
  "Process-specific burdens, residual material landfill",
  "Process-specific burdens, sanitary landfill",
  "Process-specific burdens, slag landfill",
  "Prochloraz",
  "Prohexadione calcium",
  "Propanal",
  "Propane",
  "Propionic acid",
  "Propyl amine",
  "Propylene",
  "Propylene glycol, liquid",
  "Propylene oxide, liquid",
  "Propylene, pipeline system",
  "Pumice",
  "Purge gas, rich in sodium nitrate",
  "Purified terephthalic acid",
  "Pyrazole",
  "Pyridine",
  "Pyrite ash",
  "Pyrochlore concentrate",
  "Quicklime, in pieces, loose",
  "Quicklime, milled, loose",
  "Quicklime, milled, packed",
  "Rare earth carbonate concentrate",
  "Rare earth oxide concentrate, 50% reo",
  "Rare earth oxide concentrate, 70% reo",
  "Rare earth tailings, from bastnaesite and monazite ore",
  "Raw sewage sludge",
  "Redmud from bauxite digestion",
  "Reeled raw silk hank",
  "Refinery gas",
  "Refinery sludge",
  "Reformate",
  "Refractory material, acid",
  "Refractory spent pot liner from al electrolysis",
  "Refractory, basic, packed",
  "Refractory, fireclay, packed",
  "Refractory, high aluminium oxide, packed",
  "Refrigerant r134a",
  "Reinforcing steel",
  "Residue from na-dichromate production",
  "Residue from tio2 production, chloride process",
  "Residue from tio2 production, sulfate process",
  "Residue from cooling tower",
  "Residue from mechanical treatment, it accessory",
  "Residue from mechanical treatment, cathode ray tube display",
  "Residue from mechanical treatment, desktop computer",
  "Residue from mechanical treatment, industrial device",
  "Residue from mechanical treatment, laptop computer",
  "Residue from mechanical treatment, laser printer",
  "Residue from mechanical treatment, liquid crystal display",
  "Residue from rutile production, synthetic, 56% water",
  "Residue from shredder fraction from manual dismantling",
  "Residues, mswi-wwt, ww from crt production",
  "Residues, mswi-wwt, ww from ggbfs production",
  "Residues, mswi-wwt, ww from lcd backlight production",
  "Residues, mswi-wwt, ww from lcd production",
  "Residues, mswi-wwt, ww from pv cell production",
  "Residues, mswi-wwt, ww from ammonium paratungstate production",
  "Residues, mswi-wwt, ww from black chrome coating",
  "Residues, mswi-wwt, ww from ceramic production",
  "Residues, mswi-wwt, ww from concrete production",
  "Residues, mswi-wwt, ww from glass production",
  "Residues, mswi-wwt, ww from grass refinery",
  "Residues, mswi-wwt, ww from hard fibreboard production",
  "Residues, mswi-wwt, ww from liquid crystal production",
  "Residues, mswi-wwt, ww from maize starch production",
  "Residues, mswi-wwt, ww from medium density board production",
  "Residues, mswi-wwt, ww from particle board production",
  "Residues, mswi-wwt, ww from pig iron production",
  "Residues, mswi-wwt, ww from plywood production",
  "Residues, mswi-wwt, ww from potato starch production",
  "Residues, mswi-wwt, ww from soft fibreboard production",
  "Residues, mswi-wwt, ww from tube collector production",
  "Residues, mswi-wwt, ww from vegetable oil refinery",
  "Residues, mswi-wwt, ww from wafer fabrication",
  "Residues, mswi-wwt, ww, average",
  "Residues, mswi-wwt, condensate from light oil boiler",
  "Residues, mswi-wwt, heat carrier liquid, 40% c3h8o2",
  "Residues, mswi-wwt, rainwater mineral oil storage",
  "Residues, mswi-wwt[r], ww from anaerobic digestion of whey",
  "Residues, mswi-wwt[u], ww from lorry production",
  "Residues, mswi[f]-wwt, ww from crt production",
  "Residues, mswi[f]-wwt, ww from lcd backlight production",
  "Residues, mswi[f]-wwt, ww from lcd production",
  "Residues, mswi[f]-wwt, ww from pv cell production",
  "Residues, mswi[f]-wwt, ww from black chrome coating",
  "Residues, mswi[f]-wwt, ww from ceramic production",
  "Residues, mswi[f]-wwt, ww from concrete production",
  "Residues, mswi[f]-wwt, ww from glass production",
  "Residues, mswi[f]-wwt, ww from grass refinery",
  "Residues, mswi[f]-wwt, ww from liquid crystal production",
  "Residues, mswi[f]-wwt, ww from maize starch production",
  "Residues, mswi[f]-wwt, ww from pig iron production",
  "Residues, mswi[f]-wwt, ww from plywood production",
  "Residues, mswi[f]-wwt, ww from potato starch production",
  "Residues, mswi[f]-wwt, ww from soft fibreboard production",
  "Residues, mswi[f]-wwt, ww from tube collector production",
  "Residues, mswi[f]-wwt, ww from wafer fabrication",
  "Residues, mswi[f]-wwt, ww, average",
  "Residues, mswi[f]-wwt, condensate from light oil boiler",
  "Residues, mswi[f]-wwt, heat carrier liquid, 40% c3h8o2",
  "Residues, mswi[f]-wwt, rainwater mineral oil storage",
  "Residues, mswi[f]-wwt[r], ww from anaerobic digestion of whey",
  "Residues, mswi[f]-wwt[u], ww from lorry production",
  "Resistor, auxilliaries and energy use",
  "Resistor, metal film type, through-hole mounting",
  "Resistor, surface-mounted",
  "Resistor, wirewound, through-hole mounting",
  "Resorcinol",
  "Retention aid, for paper production",
  "Rhodium",
  "Road wear emissions, lorry",
  "Road wear emissions, passenger car",
  "Rock crushing",
  "Roof tile",
  "Rosin size, for paper production",
  "Rutile, 95% titanium dioxide",
  "Salicylic acid",
  "Salt",
  "Salt tailing from potash mine",
  "Samarium oxide",
  "Samarium-europium-gadolinium oxide",
  "Sand",
  "Sand-lime brick",
  "Sanforizing, textile",
  "Sanitary ceramics",
  "Sawdust, loose, wet, measured as dry mass",
  "Sawdust, wet, measured as dry mass",
  "Scandium oxide",
  "Scrap aluminium",
  "Scrap copper",
  "Scrap lead acid battery",
  "Scrap steel",
  "Scrap tin sheet",
  "Seal, natural rubber based",
  "Section bar extrusion, aluminium",
  "Section bar rolling, steel",
  "Selenium",
  "Sewage sludge, 70% water, wwt, ww from crt production",
  "Sewage sludge, 70% water, wwt, ww from ggbfs production",
  "Sewage sludge, 70% water, wwt, ww from lcd backlight production",
  "Sewage sludge, 70% water, wwt, ww from lcd production",
  "Sewage sludge, 70% water, wwt, ww from pv cell production",
  "Sewage sludge, 70% water, wwt, ww from ammonium paratungstate production",
  "Sewage sludge, 70% water, wwt, ww from black chrome coating",
  "Sewage sludge, 70% water, wwt, ww from ceramic production",
  "Sewage sludge, 70% water, wwt, ww from concrete production",
  "Sewage sludge, 70% water, wwt, ww from glass production",
  "Sewage sludge, 70% water, wwt, ww from grass refinery",
  "Sewage sludge, 70% water, wwt, ww from hard fibreboard production",
  "Sewage sludge, 70% water, wwt, ww from liquid crystal production",
  "Sewage sludge, 70% water, wwt, ww from maize starch production",
  "Sewage sludge, 70% water, wwt, ww from medium density board production",
  "Sewage sludge, 70% water, wwt, ww from particle board production",
  "Sewage sludge, 70% water, wwt, ww from pig iron production",
  "Sewage sludge, 70% water, wwt, ww from plywood production",
  "Sewage sludge, 70% water, wwt, ww from potato starch production",
  "Sewage sludge, 70% water, wwt, ww from soft fibreboard production",
  "Sewage sludge, 70% water, wwt, ww from tube collector production",
  "Sewage sludge, 70% water, wwt, ww from vegetable oil refinery",
  "Sewage sludge, 70% water, wwt, ww from wafer fabrication",
  "Sewage sludge, 70% water, wwt, ww, average",
  "Sewage sludge, 70% water, wwt, condensate from light oil boiler",
  "Sewage sludge, 70% water, wwt, heat carrier liquid, 40% c3h8o2",
  "Sewage sludge, 70% water, wwt, rainwater mineral oil storage",
  "Sewage sludge, 70% water, wwt[r], ww from anaerobic digestion of whey",
  "Sewage sludge, 70% water, wwt[u], ww from lorry production",
  "Sewage sludge, 75% water, wwt, ww from crt production",
  "Sewage sludge, 75% water, wwt, ww from ggbfs production",
  "Sewage sludge, 75% water, wwt, ww from lcd backlight production",
  "Sewage sludge, 75% water, wwt, ww from lcd production",
  "Sewage sludge, 75% water, wwt, ww from pv cell production",
  "Sewage sludge, 75% water, wwt, ww from ammonium paratungstate production",
  "Sewage sludge, 75% water, wwt, ww from black chrome coating",
  "Sewage sludge, 75% water, wwt, ww from ceramic production",
  "Sewage sludge, 75% water, wwt, ww from concrete production",
  "Sewage sludge, 75% water, wwt, ww from glass production",
  "Sewage sludge, 75% water, wwt, ww from grass refinery",
  "Sewage sludge, 75% water, wwt, ww from hard fibreboard production",
  "Sewage sludge, 75% water, wwt, ww from liquid crystal production",
  "Sewage sludge, 75% water, wwt, ww from maize starch production",
  "Sewage sludge, 75% water, wwt, ww from medium density board production",
  "Sewage sludge, 75% water, wwt, ww from particle board production",
  "Sewage sludge, 75% water, wwt, ww from pig iron production",
  "Sewage sludge, 75% water, wwt, ww from plywood production",
  "Sewage sludge, 75% water, wwt, ww from potato starch production",
  "Sewage sludge, 75% water, wwt, ww from soft fibreboard production",
  "Sewage sludge, 75% water, wwt, ww from tube collector production",
  "Sewage sludge, 75% water, wwt, ww from vegetable oil refinery",
  "Sewage sludge, 75% water, wwt, ww from wafer fabrication",
  "Sewage sludge, 75% water, wwt, ww, average",
  "Sewage sludge, 75% water, wwt, condensate from light oil boiler",
  "Sewage sludge, 75% water, wwt, heat carrier liquid, 40% c3h8o2",
  "Sewage sludge, 75% water, wwt, rainwater mineral oil storage",
  "Sewage sludge, 75% water, wwt[r], ww from anaerobic digestion of whey",
  "Sewage sludge, 75% water, wwt[u], ww from lorry production",
  "Sewage sludge, 97% water, wwt, ww from crt production",
  "Sewage sludge, 97% water, wwt, ww from ggbfs production",
  "Sewage sludge, 97% water, wwt, ww from lcd backlight production",
  "Sewage sludge, 97% water, wwt, ww from lcd production",
  "Sewage sludge, 97% water, wwt, ww from pv cell production",
  "Sewage sludge, 97% water, wwt, ww from ammonium paratungstate production",
  "Sewage sludge, 97% water, wwt, ww from black chrome coating",
  "Sewage sludge, 97% water, wwt, ww from ceramic production",
  "Sewage sludge, 97% water, wwt, ww from concrete production",
  "Sewage sludge, 97% water, wwt, ww from glass production",
  "Sewage sludge, 97% water, wwt, ww from grass refinery",
  "Sewage sludge, 97% water, wwt, ww from hard fibreboard production",
  "Sewage sludge, 97% water, wwt, ww from liquid crystal production",
  "Sewage sludge, 97% water, wwt, ww from maize starch production",
  "Sewage sludge, 97% water, wwt, ww from medium density board production",
  "Sewage sludge, 97% water, wwt, ww from particle board production",
  "Sewage sludge, 97% water, wwt, ww from pig iron production",
  "Sewage sludge, 97% water, wwt, ww from plywood production",
  "Sewage sludge, 97% water, wwt, ww from potato starch production",
  "Sewage sludge, 97% water, wwt, ww from soft fibreboard production",
  "Sewage sludge, 97% water, wwt, ww from tube collector production",
  "Sewage sludge, 97% water, wwt, ww from vegetable oil refinery",
  "Sewage sludge, 97% water, wwt, ww from wafer fabrication",
  "Sewage sludge, 97% water, wwt, ww, average",
  "Sewage sludge, 97% water, wwt, condensate from light oil boiler",
  "Sewage sludge, 97% water, wwt, heat carrier liquid, 40% c3h8o2",
  "Sewage sludge, 97% water, wwt, rainwater mineral oil storage",
  "Sewage sludge, 97% water, wwt[r], ww from anaerobic digestion of whey",
  "Sewage sludge, 97% water, wwt[u], ww from lorry production",
  "Sewage sludge, dried",
  "Shale",
  "Shale brick",
  "Shavings, hardwood, loose, measured as dry mass",
  "Shavings, hardwood, measured as dry mass",
  "Shavings, softwood, loose, measured as dry mass",
  "Shavings, softwood, measured as dry mass",
  "Sheet rolling, aluminium",
  "Sheet rolling, chromium steel",
  "Sheet rolling, copper",
  "Sheet rolling, steel",
  "Shredder fraction after manual dismantling of used electronic product",
  "Silica fume, densified",
  "Silica sand",
  "Silicon carbide",
  "Silicon tetrachloride",
  "Silicon tetrahydride",
  "Silicon, electronics grade",
  "Silicon, metallurgical grade",
  "Silicon, multi-si, casted",
  "Silicon, single crystal, czochralski process, electronics",
  "Silicon, single crystal, czochralski process, photovoltaics",
  "Silicon, solar grade",
  "Silicone product",
  "Silky fibre",
  "Silver",
  "Silver, unrefined",
  "Slab and siding, hardwood, wet, measured as dry mass",
  "Slab and siding, softwood, wet, measured as dry mass",
  "Slag from metallurgical grade silicon production",
  "Slaughterhouse waste",
  "Sludge from fecl3 production",
  "Sludge from pulp and paper production",
  "Sludge from steel rolling",
  "Sludge, nacl electrolysis",
  "Sludge, nacl electrolysis hg",
  "Soap",
  "Soda ash, dense",
  "Soda ash, light",
  "Sodium",
  "Sodium aluminate, powder",
  "Sodium amide",
  "Sodium arsenide",
  "Sodium bicarbonate",
  "Sodium chlorate, powder",
  "Sodium chloride, brine solution",
  "Sodium chloride, powder",
  "Sodium chloroacetate",
  "Sodium cumenesulphonate",
  "Sodium cyanide",
  "Sodium dichromate",
  "Sodium dithionite, anhydrous",
  "Sodium ethoxide",
  "Sodium ethyl xanthate",
  "Sodium fluoride",
  "Sodium formate",
  "Sodium hydrogen sulfate",
  "Sodium hydrogen sulfite",
  "Sodium hydrosulfide",
  "Sodium hydroxide, without water, in 50% solution state",
  "Sodium hypochlorite, without water, in 15% solution state",
  "Sodium metasilicate pentahydrate, 58% active substance, powder",
  "Sodium methoxide",
  "Sodium nitrate",
  "Sodium nitrite",
  "Sodium oxide",
  "Sodium perborate, monohydrate, powder",
  "Sodium perborate, tetrahydrate, powder",
  "Sodium percarbonate, powder",
  "Sodium perchlorate",
  "Sodium persulfate",
  "Sodium phenolate",
  "Sodium phosphate",
  "Sodium pyrophosphate",
  "Sodium silicate, solid",
  "Sodium silicate, spray powder, 80%",
  "Sodium silicate, without water, in 37% solution state",
  "Sodium silicate, without water, in 48% solution state",
  "Sodium silver thiosulfate",
  "Sodium sulfate, anhydrite",
  "Sodium sulfide",
  "Sodium sulfite",
  "Sodium tetrafluoroborate",
  "Sodium tetrahydridoborate",
  "Sodium tripolyphosphate",
  "Soft solder, sn97cu3",
  "Soil, contaminated",
  "Solar collector glass tube, with silver mirror",
  "Solar glass, low-iron",
  "Solder, bar, sn63pb37, for electronics industry",
  "Solder, bar, sn95.5ag3.9cu0.6, for electronics industry",
  "Solder, paste, sn63pb37, for electronics industry",
  "Solder, paste, sn95.5ag3.9cu0.6, for electronics industry",
  "Solid bleached and unbleached board carton",
  "Solvent for chromatography analysis",
  "Solvent for paint",
  "Solvent, organic",
  "Spent formox catalyst base from formaldehyde production",
  "Spent activated carbon with mercury",
  "Spent activated carbon, granular",
  "Spent anion exchange resin from potable water production",
  "Spent antifreezer liquid",
  "Spent automobile catalyst",
  "Spent catalyst base from ethyleneoxide production",
  "Spent catalytic converter nox reduction",
  "Spent catalytic converter for cars",
  "Spent cation exchange resin from potable water production",
  "Spent nuclear fuel",
  "Spent pot liner from al electrolysis, carbon fraction",
  "Spent solvent mixture",
  "Spodumene",
  "Spoil from hard coal mining",
  "Spoil from lignite mining",
  "Sponge iron",
  "Sputtering target, sintered, indium tin oxide",
  "Steam, in chemical industry",
  "Stearic acid",
  "Steatite",
  "Steel in car shredder residue",
  "Steel removed by drilling, computer numerical controlled",
  "Steel removed by drilling, conventional",
  "Steel removed by milling, average",
  "Steel removed by milling, dressing",
  "Steel removed by milling, large parts",
  "Steel removed by milling, small parts",
  "Steel removed by turning, average, computer numerical controlled",
  "Steel removed by turning, average, conventional",
  "Steel removed by turning, primarily dressing, computer numerical controlled",
  "Steel removed by turning, primarily dressing, conventional",
  "Steel removed by turning, primarily roughing, computer numerical controlled",
  "Steel removed by turning, primarily roughing, conventional",
  "Steel, chromium steel 18/8",
  "Steel, chromium steel 18/8, hot rolled",
  "Steel, low-alloyed",
  "Steel, low-alloyed, hot rolled",
  "Steel, unalloyed",
  "Stibnite concentrate",
  "Stockpiling of anode slime from electrorefining of copper, anode",
  "Stone groundwood pulp",
  "Stone wool",
  "Stone wool, packed",
  "Stretch blow moulding",
  "Strontium carbonate",
  "Strontium sulfate, 90% srso4",
  "Stucco",
  "Styrene",
  "Styrene-acrylonitrile copolymer",
  "Succinic acid",
  "Sulfamic acid",
  "Sulfate pulp, bleached",
  "Sulfate pulp, unbleached",
  "Sulfidic tailing, off-site, high gold content",
  "Sulfidic tailings, from cinnabar mine operation",
  "Sulfidic tailings, from copper mine operation",
  "Sulfidic tailings, from gold mine operation",
  "Sulfidic tailings, from nickel mine operation",
  "Sulfidic tailings, from silver mine operation",
  "Sulfidic tailings, from zinc-lead mine operation",
  "Sulfidic tailings, generic",
  "Sulfite",
  "Sulfite pulp, bleached",
  "Sulfur",
  "Sulfur dichloride",
  "Sulfur dioxide, liquid",
  "Sulfur hexafluoride, liquid",
  "Sulfur stockpiling",
  "Sulfur trioxide",
  "Sulfuric acid",
  "Sulfuryl chloride",
  "Supplementary cementitious materials",
  "Switch, toggle type",
  "Synthetic graphite, battery grade",
  "Synthetic rubber",
  "Tall oil, crude",
  "Tallow, unrefined",
  "Tantalum concentrate, 30% ta2o5",
  "Tantalum powder, capacitor-grade",
  "Tap water",
  "Tebuconazole",
  "Tellurium, semiconductor-grade",
  "Tempering, flat glass",
  "Terbium oxide",
  "Terbium-dysprosium oxide",
  "Tert-butyl amine",
  "Tetrachloroethylene",
  "Tetraethyl orthosilicate",
  "Tetrafluoroethylene",
  "Tetrafluoroethylene film, on glass",
  "Tetrahydrofuran",
  "Textile, jute",
  "Textile, kenaf",
  "Textile, knit cotton",
  "Textile, nonwoven polyester",
  "Textile, nonwoven polypropylene",
  "Textile, silk",
  "Textile, woven cotton",
  "Thermal plaster, outdoor",
  "Thermo-mechanical pulp",
  "Thermoforming of plastic sheets",
  "Thermoforming, with calendering",
  "Thionyl chloride",
  "Thulium oxide",
  "Tin",
  "Tin concentrate",
  "Tin dioxide",
  "Tin slag",
  "Tinplate scrap, sorted",
  "Tinplate, in mixed metal scrap",
  "Tissue paper",
  "Titania slag, 85% titanium dioxide",
  "Titania slag, 94% titanium dioxide",
  "Titanium",
  "Titanium dioxide",
  "Titanium sponge",
  "Titanium tetrachloride",
  "Titanium zinc plate, without pre-weathering",
  "Titanium, triple-melt",
  "Toluene diisocyanate",
  "Toluene, liquid",
  "Toner, black, powder",
  "Toner, colour, powder",
  "Transformer, high voltage use",
  "Transformer, low voltage use",
  "Transistor, auxilliaries and energy use",
  "Transistor, surface-mounted",
  "Transistor, wired, big size, through-hole mounting",
  "Transistor, wired, small size, through-hole mounting",
  "Trichloroacetic acid",
  "Trichloroborane",
  "Trichloroethylene",
  "Trichloromethane",
  "Trichloropropane",
  "Triclopyr",
  "Triethanolamine",
  "Triethyl amine",
  "Triethylene glycol",
  "Trifluoroacetic acid",
  "Trifluoromethane",
  "Trimesoyl chloride",
  "Trimethyl borate",
  "Trimethylamine",
  "Trinexapac-ethyl",
  "Triphenyl phosphate",
  "Tris(2,4-ditert-butylphenyl) phosphite",
  "Trisodium phosphate",
  "Tube insulation, elastomere",
  "Tungsten carbide powder",
  "Tungsten concentrate",
  "Turpentine",
  "Tyre wear emissions, lorry",
  "Tyre wear emissions, passenger car",
  "Uranium hexafluoride",
  "Uranium ore, as u",
  "Uranium, enriched 3.0%, in fuel element for light water reactor",
  "Uranium, enriched 3.8%, in fuel element for light water reactor",
  "Uranium, enriched 3.9%, in fuel element for light water reactor",
  "Uranium, enriched 4%, in fuel element for light water reactor",
  "Uranium, enriched 4.2%, in fuel element for light water reactor",
  "Uranium, in yellowcake",
  "Urea formaldehyde foam slab, hard",
  "Urea formaldehyde foam, in situ foaming",
  "Urea formaldehyde resin",
  "Used it accessory",
  "Used li-ion battery",
  "Used ni-metal hydride battery",
  "Used beverage cans",
  "Used cable",
  "Used capacitor",
  "Used cathode ray tube display",
  "Used desktop computer",
  "Used fluorescent lamp",
  "Used glider, electric scooter",
  "Used glider, passenger car",
  "Used industrial electronic device",
  "Used internal combustion engine, passenger car",
  "Used laptop computer",
  "Used liquid crystal display",
  "Used liquid crystal display module",
  "Used nitrate salts, for solar power application",
  "Used perfluoropentane",
  "Used powertrain from electric passenger car, manual dismantling",
  "Used powertrain, electric scooter",
  "Used printed wiring boards",
  "Used printer, laser",
  "Used refrigerant r-12",
  "Used refrigerant r-600a",
  "Used refrigerant r134a",
  "Used smartphone",
  "Used tablet",
  "Used toner module, laser printer, black/white",
  "Used toner module, laser printer, colour",
  "Used tyre",
  "Used vegetable cooking oil",
  "Used vegetable cooking oil, purified",
  "Venting of argon, crude, liquid",
  "Venting of nitrogen, liquid",
  "Vermiculite",
  "Vinyl acetate",
  "Vinyl carbonate",
  "Vinyl chloride",
  "Vinyl fluoride",
  "Washing, drying and finishing laundry",
  "Waste aluminium",
  "Waste asphalt",
  "Waste bamboo residues",
  "Waste bitumen",
  "Waste bitumen sheet",
  "Waste brick",
  "Waste building wood, chrome preserved",
  "Waste bulk iron, excluding reinforcement",
  "Waste cement in concrete and mortar",
  "Waste cement, hydrated",
  "Waste cement-fibre slab",
  "Waste cement-fibre slab, dismantled",
  "Waste concrete",
  "Waste concrete gravel",
  "Waste concrete, not reinforced",
  "Waste electric and electronic equipment",
  "Waste electric wiring",
  "Waste emulsion paint",
  "Waste emulsion paint, on wall",
  "Waste emulsion paint, on wood",
  "Waste emulsion paint, separated",
  "Waste expanded polystyrene",
  "Waste fibreboard",
  "Waste foundry sand",
  "Waste frit from cathode ray tube production",
  "Waste glass",
  "Waste glass pane in burnable frame",
  "Waste glass sheet",
  "Waste graphical paper",
  "Waste gypsum",
  "Waste gypsum plasterboard",
  "Waste mineral oil",
  "Waste mineral plaster",
  "Waste mineral wool",
  "Waste mineral wool, for final disposal",
  "Waste mixed aggregates, from demolition",
  "Waste newspaper",
  "Waste packaging glass, unsorted",
  "Waste packaging paper",
  "Waste paint",
  "Waste paint on metal",
  "Waste paint on wall",
  "Waste paint on wood",
  "Waste paper, sorted",
  "Waste paper, unsorted",
  "Waste paperboard",
  "Waste paperboard, sorted",
  "Waste paperboard, unsorted",
  "Waste plaster-cardboard sandwich",
  "Waste plastic plaster",
  "Waste plastic plaster, for final disposal",
  "Waste plastic, consumer electronics",
  "Waste plastic, consumer electronics, sorted",
  "Waste plastic, consumer electronics, unsorted",
  "Waste plastic, industrial electronics",
  "Waste plastic, mixture",
  "Waste polyethylene",
  "Waste polyethylene terephthalate",
  "Waste polyethylene terephthalate, for recycling, sorted",
  "Waste polyethylene terephthalate, for recycling, unsorted",
  "Waste polyethylene, for recycling, sorted",
  "Waste polyethylene, for recycling, unsorted",
  "Waste polyethylene/polypropylene product",
  "Waste polypropylene",
  "Waste polystyrene",
  "Waste polystyrene isolation, flame-retardant",
  "Waste polyurethane",
  "Waste polyurethane foam",
  "Waste polyurethane seal",
  "Waste polyvinylchloride",
  "Waste polyvinylchloride product",
  "Waste polyvinylfluoride",
  "Waste reinforced concrete",
  "Waste reinforced plasterboard",
  "Waste reinforcement steel",
  "Waste rubber, unspecified",
  "Waste sealing sheet, polyethylene",
  "Waste sealing sheet, polyvinylchloride",
  "Waste textile, soiled",
  "Waste vapour barrier, flame-retarded",
  "Waste wire plastic",
  "Waste wood pole, chrome preserved",
  "Waste wood, post-consumer",
  "Waste wood, untreated",
  "Waste x-ray film",
  "Waste yarn and waste textile",
  "Waste zeolite",
  "Waste, electrical and electronic cables",
  "Waste, from silicon wafer production",
  "Waste, from silicon wafer production, inorganic",
  "Waste, pneumatic tyres",
  "Water discharge from petroleum extraction, offshore",
  "Water discharge from petroleum/natural gas extraction, onshore",
  "Water, completely softened",
  "Water, decarbonised",
  "Water, deionised",
  "Water, harvested from rainwater",
  "Water, ultrapure",
  "Wax, lost-wax casting",
  "Weaving, synthetic fibre",
  "White lined chipboard carton",
  "White spirit",
  "Wire drawing, copper",
  "Wire drawing, steel",
  "Wood ash mixture, pure",
  "Wood chipping, industrial residual wood, stationary electric chipper",
  "Wood chips and particles, willow",
  "Wood chips, dry, measured as dry mass",
  "Wood chips, from post-consumer wood, measured as dry mass",
  "Wood chips, wet, measured as dry mass",
  "Wood pellet, measured as dry mass",
  "Wood preservation, dipping/immersion method, organic solvent-based, indoor use, dry",
  "Wood preservation, dipping/immersion method, organic solvent-based, indoor use, occasionally wet",
  "Wood preservation, dipping/immersion method, organic solvent-based, outdoor use, no ground contact",
  "Wood preservation, dipping/immersion method, water-based, indoor use, dry",
  "Wood preservation, dipping/immersion method, water-based, indoor use, occasionally wet",
  "Wood preservation, dipping/immersion method, water-based, outdoor use, no ground contact",
  "Wood preservation, hot/cold dipping, creosote, outdoor use, ground contact",
  "Wood preservation, oscillating pressure method, inorganic salt, containing cr, outdoor use, ground contact",
  "Wood preservation, oscillating pressure method, organic salt, cr-free, outdoor use, ground contact",
  "Wood preservation, pressure vessel, creosote, outdoor use, ground contact",
  "Wood preservation, spray tunnel/deluging, organic solvent-based, indoor use, dry",
  "Wood preservation, spray tunnel/deluging, organic solvent-based, indoor use, occasionally wet",
  "Wood preservation, spray tunnel/deluging, organic solvent-based, outdoor use, no ground contact",
  "Wood preservation, spray tunnel/deluging, water-based, indoor use, dry",
  "Wood preservation, spray tunnel/deluging, water-based, indoor use, occasionally wet",
  "Wood preservation, spray tunnel/deluging, water-based, outdoor use, no ground contact",
  "Wood preservation, vacuum pressure method, inorganic salt, containing cr, outdoor use, ground contact",
  "Wood preservation, vacuum pressure method, organic salts, cr-free, outdoor use, ground contact",
  "Wood preservative, creosote",
  "Wood preservative, inorganic salt, containing cr",
  "Wood preservative, organic salt, cr-free",
  "Wood preservative, organic, indoor use, dry",
  "Wood preservative, organic, indoor use, occasionally wet",
  "Wood preservative, organic, outdoor use, no ground contact",
  "Wood preservative, water-based, indoor use, dry",
  "Wood preservative, water-based, indoor use, occasionally wet",
  "Wood preservative, water-based, outdoor use, no ground contact",
  "Wood wool",
  "Woven bamboo mat",
  "Xenon, gaseous",
  "Xylene",
  "Yarn, cotton",
  "Yarn, jute",
  "Yarn, kenaf",
  "Yarn, silk",
  "Ytterbium oxide",
  "Yttrium oxide",
  "Zeolite, powder",
  "Zeolite, slurry, without water, in 50% solution state",
  "Zinc",
  "Zinc concentrate",
  "Zinc in car shredder residue",
  "Zinc monosulfate",
  "Zinc oxide",
  "Zinc scrap, post-consumer",
  "Zinc slag",
  "Zinc sulfide",
  "Zineb",
  "Zircon",
  "Zirconium oxide",
  "Zirconium sponge, nuclear-grade",
  "Zirconium tetrachloride",
]

const general = [
  "Polyvinylchloride / PVC (general)",
  "Metal (general)",
  "Plastic (general) ",
  "Copper (general)",
  "Glass (general)",
  "Iron (general)",
  "Fabric / Cloth (general)",
  "Steel (general)",
  "Acrylonitrile-butadiene-styrene (ABS)",
]

export default [...general, ...ecoinvent]
