export default {
  "Agricultural and forestry machinery": [
    "Agricultural machinery, tillage",
    "Liquid manure tank trailer",
    "Agricultural machinery, unspecified",
    "Harvester",
    "Tractor, 4-wheel, agricultural",
    "Agricultural trailer",
  ],
  "Articles of concrete, cement and plaster": [
    "Autoclaved aerated concrete block",
    "Concrete roof tile",
    "Anhydrite floor",
    "Fibre cement corrugated slab",
    "Flyash brick",
    "Concrete block",
    "Sand-lime brick",
    "Stucco",
    "Granulated blast furnace slag",
    "Fibre cement facing tile",
    "Fibre cement facing tile, large format",
    "Fibre cement facing tile, small format",
    "Cement cast plaster floor",
    "Fibre cement roof slate",
    "Cement tile",
  ],
  "Basic chemicals": [
    "Prohexadione calcium",
    "Tin dioxide",
    "Phosphoric acid, industrial grade, without water, in 85% solution state",
    "Carbon tetrachloride",
    "Sodium hydroxide, without water, in 50% solution state",
    "Gallium, semiconductor-grade",
    "Butyrolactone",
    "Optical brighteners, for paper production",
    "Maleic hydrazide",
    "Battery cell, li-ion, lfp",
    "Cobalt sulfate",
    "Sodium bicarbonate",
    "Dimethylaminopropylamine",
    "Acrylonitrile",
    "Phenyl isocyanate",
    "Sodium oxide",
    "2-cyclopentone",
    "Propane",
    "Uranium, enriched 3.8%, in fuel element for light water reactor",
    "Maleic anhydride",
    "Sodium hypochlorite, without water, in 15% solution state",
    "Tetraethyl orthosilicate",
    "Nmc811 oxide",
    "Acetylene",
    "1-naphthylacetic acid",
    "Iodine",
    "Diborane",
    "Methanol, from biomass",
    "Diethylene glycol",
    "Phosphorus trichloride",
    "Nmc111 hydroxide",
    "Glycerine",
    "4-tert-butylbenzaldehyde",
    "Ethylene glycol monoethyl ether",
    "Lithium hydroxide",
    "Alpha-picoline",
    "Triethanolamine",
    "Propylene glycol, liquid",
    "Zinc oxide",
    "1-butanol",
    "Epichlorohydrin",
    "Cyclohexane",
    "Trifluoroacetic acid",
    "Helium",
    "3-methylpyridine",
    "Lithium brine, 6.7 % li",
    "Acetaldehyde",
    "Sulfuryl chloride",
    "Sulfur dioxide, liquid",
    "Nuclear fuel element, for pressure water reactor, uo2 3.9% & mox",
    "Calcium carbonate, precipitated",
    "Oxygen, liquid",
    "Sodium methoxide",
    "Cadmium, semiconductor-grade",
    "Butyl acetate",
    "Sodium amide",
    "Cyanoacetic acid",
    "Distiller's dried grains with solubles",
    "Ethyl acetate",
    "Acetic anhydride",
    "Acrolein",
    "Nmc111 oxide",
    "Methyl ethyl ketone",
    "Methyl tert-butyl ether",
    "Lithium hexafluorophosphate",
    "Daminozide",
    "Ethyl tert-butyl ether",
    "N-methyl-2-pyrrolidone",
    "Boron trifluoride",
    "Dimethyl hexanediol",
    "Ethanol, without water, in 99.7% solution state, from fermentation",
    "Phthalimide",
    "Esters of versatic acid",
    "Dioxane",
    "Metazachlor",
    "1,1-difluoroethane, hfc-152a",
    "Graphite, battery grade",
    "Iron(iii) sulfate, without water, in 12.5% iron solution state",
    "Piperidine",
    "Carboxymethyl cellulose, powder",
    "Dimethyl ether",
    "Sodium aluminate, powder",
    "Chlorpropham",
    "Soda ash, dense",
    "Krypton, gaseous",
    "Dimethyl hexynediol",
    "Nuclear fuel element, for pressure water reactor, uo2 4.2% & mox",
    "Trichloroborane",
    "Ethylene dichloride",
    "Aniline",
    "Acetic acid, without water, in 98% solution state",
    "Cyclohexanone",
    "Silicon, single crystal, czochralski process, photovoltaics",
    "Isobutanol",
    "Carbon black",
    "Triethyl amine",
    "Methanol",
    "6-benzyladenine",
    "Butyl acrylate",
    "Uranium, enriched 3.0%, in fuel element for light water reactor",
    "Hydrochloric acid, without water, in 30% solution state",
    "Hexamethyldisilazane",
    "Dimethyl sulfoxide",
    "Uranium, enriched 4.2%, in fuel element for light water reactor",
    "Dioctyl terephthalate",
    "Propionic acid",
    "Lithium iron phosphate",
    "Sulfur dichloride",
    "Ethylene bromide",
    "Cumene",
    "Trichloroacetic acid",
    "Disodium disulphite",
    "De-icer",
    "Ozone, liquid",
    "Pyridine",
    "Propylene oxide, liquid",
    "Bromopropane",
    "2,4-dinitrotoluene",
    "Imidazole",
    "Cryolite",
    "Succinic acid",
    "Benzaldehyde",
    "Sodium sulfate, anhydrite",
    "Pentane",
    "Silicon tetrahydride",
    "Acetone, liquid",
    "Sulfur trioxide",
    "Refrigerant r134a",
    "Arsine",
    "Sodium hydrosulfide",
    "Phosphorous chloride",
    "Chlorine, gaseous",
    "Dinitrogen tetroxide",
    "Carbon dioxide, liquid",
    "Hydrogen sulfide",
    "Potassium permanganate",
    "Sodium sulfide",
    "Cadmium telluride, semiconductor-grade",
    "Venting of argon, crude, liquid",
    "Frit, for ceramic tile",
    "Chlorosulfonic acid",
    "Sulfur hexafluoride, liquid",
    "Ethylamine",
    "Xylene",
    "Anthraquinone",
    "Prochloraz",
    "Soda ash, light",
    "Strontium carbonate",
    "P-chlorophenol",
    "Boron carbide",
    "Ethylene glycol diethyl ether",
    "Vinyl fluoride",
    "Nuclear fuel element, for pressure water reactor, uo2 3.8% & mox",
    "Stearic acid",
    "2-nitroaniline",
    "Acetonitrile",
    "Iron sulfate",
    "Ethyl benzene",
    "Silicon, multi-si, casted",
    "Potassium perchlorate",
    "Allyl chloride",
    "Hydrogen cyanide",
    "Isopropylamine",
    "Melamine",
    "P-dichlorobenzene",
    "Tris(2,4-ditert-butylphenyl) phosphite",
    "Fatty acid",
    "Oxalic acid",
    "Methyl acetate",
    "Dimethyl malonate",
    "Dichlobenil",
    "Sodium ethoxide",
    "Polysulfone",
    "Para-phenylene diamine",
    "Methallylchloride",
    "2-methyl-2-butanol",
    "Polyaluminium chloride",
    "Methyl-3-methoxypropionate",
    "Hydrazine sulfate",
    "Butyldiglycol acetate",
    "Barium hydroxide",
    "Thionyl chloride",
    "Formic acid",
    "Hydrogen fluoride",
    "Bagasse, from sweet sorghum",
    "Iron(iii) chloride, without water, in a 12% iron solution state",
    "Iron(iii) chloride, without water, in 14% iron solution state",
    "Indolylbutyric acid",
    "Phosphorus, white, liquid",
    "Chemical, inorganic",
    "Hydroxylamine",
    "Isopropanol",
    "Pitch despergents, in paper production",
    "Sodium nitrite",
    "Trimesoyl chloride",
    "1-methoxy-2-propanol",
    "Phthalic anhydride",
    "Indium",
    "Vinyl carbonate",
    "Calcium carbide, technical grade",
    "Dichloropropene",
    "Lithium carbonate",
    "Activated bentonite",
    "Activated silica",
    "2-pyridinol",
    "Dichloromethane",
    "1-pentanol",
    "Phosgene, liquid",
    "Carbon disulfide",
    "Adipic acid",
    "Chlorine dioxide",
    "Silicon, solar grade",
    "Methyl iodide",
    "Ethanol, without water, in 99.7% solution state, from ethylene",
    "Trichloropropane",
    "Triethylene glycol",
    "Chlormequat chloride",
    "Cyanuric chloride",
    "Sodium sulfite",
    "3-methyl-1-butanol",
    "Methylchloride",
    "Trifluoromethane",
    "Zirconium oxide",
    "Polyacrylamide",
    "Butane",
    "Venting of nitrogen, liquid",
    "N,n-dimethylformamide",
    "Acetyl chloride",
    "Tetrahydrofuran",
    "Sodium silicate, solid",
    "Salicylic acid",
    "Dimethyl carbonate",
    "Synthetic graphite, battery grade",
    "Titanium dioxide",
    "Sodium",
    "Sodium dichromate",
    "Hexamethylenediamine",
    "Ammonium nitrite",
    "Methyl acrylate",
    "Chloridazon",
    "Mepiquat chloride",
    "Isophorondiisocyante",
    "Retention aid, for paper production",
    "Potassium carbonate",
    "Chlorodifluoromethane",
    "Plasticiser, for concrete, based on sulfonated melamine formaldehyde",
    "Argon, crude, liquid",
    "Cyclohexanol",
    "Fluorine, liquid",
    "2,5-dimethylhexane-2,5-dihydroperoxide",
    "Sodium ethyl xanthate",
    "Sodium phenolate",
    "Zinc sulfide",
    "Dioctyl adipate",
    "Lithium",
    "Epoxy resin, liquid",
    "Glycine",
    "Resorcinol",
    "Boric oxide",
    "Calcium chloride",
    "Potassium hydroxide",
    "Aluminium sulfate, powder",
    "Cathode, lfp, for li-ion battery",
    "4-methyl-2-pentanone",
    "Trichloroethylene",
    "O-chlorobenzaldehyde",
    "Nitric oxide",
    "Silicon, electronics grade",
    "2,4-dichlorophenol",
    "Benzaldehyde-2-sulfonic acid",
    "Fodder yeast",
    "2-methyl-1-butanol",
    "Decabromodiphenyl ether",
    "Nuclear fuel element, for pressure water reactor, uo2 4.2% centrifuge & mox",
    "Chloronitrobenzene",
    "Chloromethyl methyl ether",
    "Silicon tetrachloride",
    "Trimethyl borate",
    "Nitrogen, liquid",
    "Propyl amine",
    "Methyl formate",
    "Nitrous oxide",
    "Pentaerythritol",
    "1-propanol",
    "Ethylene carbonate",
    "Sodium chloroacetate",
    "Tebuconazole",
    "Triclopyr",
    "Chloroacetyl chloride",
    "Sodium dithionite, anhydrous",
    "Paclobutrazol",
    "Inert gas for discharge lamps",
    "Lauric diethanolamide",
    "Aluminium sulfate, without water, in 4.33% aluminium solution state",
    "Phenol",
    "Sodium nitrate",
    "Trinexapac-ethyl",
    "Hydrazine",
    "Sulfamic acid",
    "Sodium formate",
    "Manganese sulfate",
    "Hydroquinone",
    "O-nitrophenol",
    "Hexamethylene-1,6-diisoncyanate",
    "Maneb",
    "Methacrylic acid",
    "Helium, crude stockpiling",
    "Dimethylamine borane",
    "Benzyl chloride",
    "Cadmium sulfide, semiconductor-grade",
    "Nca oxide",
    "Copper oxide",
    "Aminopyridine",
    "Citric acid",
    "Dimethyl sulfate",
    "Sodium hydrogen sulfite",
    "Sodium tetrafluoroborate",
    "Borax, anhydrous, powder",
    "Sodium tetrahydridoborate",
    "Copper carbonate",
    "2,4-di-tert-butylphenol",
    "Dtpa, diethylenetriaminepentaacetic acid",
    "Enriched uranium, 4.2%",
    "Chlorine, liquid",
    "Polydimethylsiloxane",
    "Tellurium, semiconductor-grade",
    "2-butanol",
    "Nuclear fuel element, for boiling water reactor, uo2 4.0% & mox",
    "Benzyl alcohol",
    "2,4-dichlorotoluene",
    "Ethylene glycol",
    "Ortho-phenylene diamine",
    "Lithium sulfate",
    "P-nitrotoluene",
    "Dimethyldichlorosilane",
    "Toluene, liquid",
    "Electrolyte, koh, lioh additive",
    "1-methylcyclopropene",
    "Sodium silicate, spray powder, 80%",
    "Sodium phosphate",
    "Bisphenol a, powder",
    "Monochlorobenzene",
    "Diethyl ether, without water, in 99.95% solution state",
    "Isopropyl acetate",
    "Carbon monoxide",
    "Aluminium fluoride",
    "Grass fibre",
    "Diethanolamine",
    "Propanal",
    "Chromium oxide, flakes",
    "3-methyl-1-butyl acetate",
    "Neutralising agent, sodium hydroxide-equivalent",
    "Dipropylene glycol monomethyl ether",
    "Manganese(iii) oxide",
    "Ethanol, without water, in 99.7% solution state, from fermentation, vehicle grade",
    "Perfluoropentane",
    "Lithium manganese oxide",
    "Sodium arsenide",
    "Sodium chlorate, powder",
    "Edta, ethylenediaminetetraacetic acid",
    "Dipropyl amine",
    "Sulfur stockpiling",
    "Tetrachloroethylene",
    "Chloropropionic acid",
    "Manganese dioxide",
    "Acrylic acid",
    "Monochloropentafluoroethane",
    "Fluazifop-butyl",
    "Aluminium chloride",
    "Argon, liquid",
    "Bromoxynil",
    "Sulfite",
    "Cyanogen chloride",
    "Acetanilide",
    "Tert-butyl amine",
    "Trichloromethane",
    "Sodium perchlorate",
    "Sodium silicate, without water, in 48% solution state",
    "Azodicarbonamide",
    "Dodecanol",
    "Xenon, gaseous",
    "O-dichlorobenzene",
    "Sodium pyrophosphate",
    "Isobutyl acetate",
    "Triphenyl phosphate",
    "Methane sulfonic acid",
    "Dimethylamine",
    "Fluorescent whitening agent, das1, triazinylaminostilben type",
    "Lithium fluoride",
    "Phosphorus pentachloride",
    "Formaldehyde",
    "Mox fuel element, for light water reactor",
    "Gallium, in bayer liquor from aluminium production",
    "Fatty alcohol",
    "Morpholine",
    "Iron(ii) chloride",
    "Benzoic acid",
    "Chloroacetic acid",
    "Ioxynil",
    "Copper sulfate",
    "Nitrobenzene",
    "Silicon, single crystal, czochralski process, electronics",
    "Methylamine",
    "Sodium hydrogen sulfate",
    "Trimethylamine",
    "O-aminophenol",
    "Cadmium chloride, semiconductor-grade",
    "Barium sulfide",
    "Zineb",
    "Phenyl acetic acid",
    "Ammonium chloride",
    "Ethane",
    "Nitrous dioxide",
    "Amidosulfuron",
    "Ethylenediamine",
    "Dimethyl sulfide",
    "Lactic acid",
    "Trisodium phosphate",
    "Nuclear fuel element, for pressure water reactor, uo2 4.0% & mox",
    "Zinc monosulfate",
    "Adiponitrile",
    "Glyoxal",
    "Sodium fluoride",
    "Battery, li-ion, lfp, rechargeable, prismatic",
    "Ammonium thiocyanate",
    "Lithium chloride",
    "Ethylene glycol dimethyl ether",
    "Phosphorus oxychloride",
    "Enzymes",
    "N-olefins",
    "2,6-di-tert-butylphenol",
    "Iron (iii) chloride, without water, in 40% solution state",
    "Benzal chloride",
    "Sodium cyanide",
    "Pyrazole",
    "4-tert-butyltoluene",
    "Sodium cumenesulphonate",
    "Acetoacetic acid",
    "O-chlorotoluene",
    "Butane-1,4-diol",
    "Aluminium hydroxide",
    "O-cresol",
    "Uranium, enriched 4%, in fuel element for light water reactor",
    "Barium carbonate",
    "Isohexane",
    "Uranium, enriched 3.9%, in fuel element for light water reactor",
    "Hexafluoroethane",
    "Fluorescent whitening agent, distyrylbiphenyl type",
    "Sodium silver thiosulfate",
    "Sodium silicate, without water, in 37% solution state",
    "Isobutane",
    "Nca hydroxide",
    "Deinking emulsion, in paper production",
    "Alpha-naphthol",
    "Hydrogen peroxide, without water, in 50% solution state",
    "Uranium hexafluoride",
    "Dimethylacetamide",
    "P-nitrophenol",
    "Bromine",
    "Ethephon",
    "Styrene",
    "Sodium persulfate",
    "Ethylene oxide",
    "Anthranilic acid",
    "Barium oxide",
    "Nmc811 hydroxide",
    "Monoethanolamine",
    "Methylcyclohexane",
    "Alkylketene dimer sizing agent, for paper production",
  ],
  "Basic chemicals, fertilizers and nitrogen compounds, plastics": [
    "Chemical, organic",
  ],
  "Basic iron and steel": [
    "Hot rolling, steel",
    "Ferrosilicon",
    "Sponge iron",
    "Steel, chromium steel 18/8",
    "Chromium steel pipe",
    "Electric arc furnace secondary metallurgy slag, for recovery",
    "Steel, chromium steel 18/8, hot rolled",
    "Steel, low-alloyed",
    "Ferroniobium, 66% nb",
    "Iron sinter",
    "Cast iron",
    "Pig iron",
    "Iron pellet",
    "Reinforcing steel",
    "Steel, low-alloyed, hot rolled",
    "Sheet rolling, chromium steel",
    "Ferromanganese, high-coal, 74.5% mn",
    "Wire drawing, steel",
    "Ferrochromium, high-carbon, 55% cr",
    "Drawing of pipe, steel",
    "Section bar rolling, steel",
    "Forging, steel",
    "Iron-nickel-chromium alloy",
    "Electric arc furnace slag, for recovery",
    "Ferrochromium, high-carbon, 68% cr",
    "Ferronickel",
    "Steel, unalloyed",
    "Sheet rolling, steel",
  ],
  "Basic precious and other non-ferrous metals": [
    "Rare earth tailings, from bastnaesite and monazite ore",
    "Sheet rolling, copper",
    "Precious metal from electronics scrap, in anode slime",
    "Aluminium alloy, almg3",
    "Rutile, 95% titanium dioxide",
    "Copper, cathode",
    "Magnesium chloride, from zirconium sponge production",
    "Lead concentrate stockpiling",
    "Copper-rich materials",
    "Copper, anode",
    "Cadmium",
    "Brass",
    "Metal catalyst for catalytic converter",
    "Titanium sponge",
    "Magnesium, for reuse in hafnium sponge production",
    "Process-specific burdens, import of copper to switzerland",
    "Nickel, class 1",
    "Manganese",
    "Hafnium sponge",
    "Scandium oxide",
    "Scrap lead acid battery",
    "Aluminium scrap, new",
    "Aluminium oxide, metallurgical",
    "Zirconium sponge, nuclear-grade",
    "Magnesium-alloy, az91, diecast",
    "Palladium",
    "Selenium",
    "Non-fe-co-metals, from used li-ion battery, pyrometallurgical processing",
    "Copper telluride cement",
    "Nickel concentrate, 7% ni",
    "Magnesium-alloy, az91",
    "Aluminium alloy, metal matrix composite",
    "Tantalum powder, capacitor-grade",
    "Crust from parkes process for lead production",
    "Lead",
    "Antimony",
    "Titanium, triple-melt",
    "Gold-silver, ingot",
    "Tungsten carbide powder",
    "Zirconium tetrachloride",
    "Molybdenum",
    "Non-fe-co-metals, from li-ion battery, hydrometallurgical processing",
    "Aluminium alloy, alli",
    "Indium rich leaching residues, from zinc production",
    "Indium rich leaching residues, from zinc production stockpiling",
    "Electronics scrap",
    "Metal part of electronics scrap, in copper, anode",
    "Cobalt",
    "Nickel-rich materials",
    "Copper scrap, sorted, pressed",
    "Aluminium, primary, liquid",
    "Sheet rolling, aluminium",
    "Ammonium paratungstate",
    "Molybdenum trioxide",
    "Magnesium chloride, from hafnium sponge production",
    "Leach residue from copper production",
    "Aluminium, wrought alloy",
    "Spent automobile catalyst",
    "Aluminium, primary, cast alloy slab from continuous casting",
    "Titanium tetrachloride",
    "Beryllium",
    "Aluminium oxide, non-metallurgical",
    "Chromium",
    "Aluminium, primary, ingot",
    "Silicon, metallurgical grade",
    "Aluminium, cast alloy",
    "Stockpiling of anode slime from electrorefining of copper, anode",
    "Hafnium tetrachloride",
    "Anode slime from electrorefining of copper, anode",
    "Titanium",
    "Copper cake",
    "Titanium zinc plate, without pre-weathering",
    "Nickel concentrate, 16% ni",
    "Magnesium chloride, from titanium sponge production",
    "Zinc",
    "Cadmium sludge from zinc electrolysis",
    "Beryllium hydroxide",
    "Rhodium",
    "Chlorine, for reuse in titanium tetrachloride production",
    "Magnesium, for reuse in zirconium sponge production",
    "Chlorine, for reuse in zirconium and hafnium tetrachloride production",
    "Platinum",
    "Section bar extrusion, aluminium",
    "Magnesium, for reuse in titanium sponge production",
    "Cadmium sludge from zinc electrolysis stockpiling",
    "Wire drawing, copper",
    "Magnesium",
    "Bronze",
  ],
  "Batteries and accumulators": [
    "Electrode, negative, ni",
    "Electrolyte, for solid oxide fuel cell",
    "Cathode, limn2o4, for li-ion battery",
    "High voltage system, for li-ion battery",
    "Cathode, nmc111, for li-ion battery",
    "Battery, nimh, rechargeable, prismatic",
    "Integrated battery interface system, for li-ion battery",
    "Battery module packaging, li-ion",
    "Cathode, nca, for li-ion battery",
    "Low voltage system, for li-ion battery",
    "Battery, li-ion, limn2o4, rechargeable, prismatic",
    "Battery cell, li-ion, limn2o4",
    "Battery, li-ion, nmc111, rechargeable, prismatic",
    "Anode, silicon coated graphite, for li-ion battery",
    "Battery, lead acid, rechargeable, stationary",
    "Battery cell, li-ion, nmc811",
    "Battery, li-ion, nmc811, rechargeable, prismatic",
    "Battery, li-ion, nca, rechargeable, prismatic",
    "Battery management system, for li-ion battery",
    "Cathode, nmc811, for li-ion battery",
    "Battery cell, li-ion, nca",
    "Electrode, negative, lic6",
    "Battery, nacl",
    "Electrode, positive, lani5",
    "Anode, graphite, for li-ion battery",
    "Battery separator",
    "Battery cell, li-ion, nmc111",
  ],
  "Beverage crops": [
    "Mulberry leaves",
    "Cocoa bean",
    "Coffee, green bean",
    "Tea, dried",
  ],
  "Cattle and buffaloes": [
    "Weaned heifers, live weight",
    "Cow milk",
    "Weaned calves, live weight",
    "Cattle for slaughtering, live weight",
    "Red meat, live weight",
  ],
  "Cement, lime and plaster": [
    "Thermal plaster, outdoor",
    "Cement, cem ii/b-v",
    "Base plaster",
    "Light mortar",
    "Gypsum plasterboard",
    "Inert filler",
    "Cement, cem ii/a-v",
    "Cement, cem iii/b",
    "Waste foundry sand",
    "Cement, cem ii/b-s",
    "Cement, art",
    "Cement, type ip/p",
    "Cement, unspecified",
    "Inert waste",
    "Cement, cp iv",
    "Cement, cem ii/a",
    "Cement, portland slag",
    "Pyrite ash",
    "Cover plaster, organic",
    "Cement, cem iii/c",
    "Cement, cem ii/b-l",
    "Cover plaster, mineral",
    "Silica fume, densified",
    "Cement, cem v/a",
    "Cement, cem iii/a",
    "Cement, cem v/b",
    "Lime, hydrated, loose weight",
    "Cement, cp ii-z",
    "Cement, cp ii-e",
    "Adhesive mortar",
    "Cement, type i (sm)",
    "Clinker",
    "Soil, contaminated",
    "Lime, hydrated, packed",
    "Cement, type is",
    "Cement, cem ii/a-s",
    "Cement, cp iii",
    "Quicklime, milled, packed",
    "Supplementary cementitious materials",
    "Quicklime, milled, loose",
    "Cement, type i-pm",
    "Cement, cem iv/b",
    "Plaster mixing",
    "Spent catalytic converter nox reduction",
    "Cement, type ico",
    "Cement mortar",
    "Cement, type s",
    "Lime, hydraulic",
    "Cement, type general use",
    "Sewage sludge, dried",
    "Cement, cem ii/a-l",
    "Cement, portland",
    "Gypsum fibreboard",
    "Anhydrite",
    "Cement, zn/d, new alternative constituents 36-50%, in conformity with sia 2049",
    "Quicklime, in pieces, loose",
    "Anhydrite, burned",
    "Cement, cem iv/a",
    "Cement, cp v rs",
    "Lime mortar",
    "Cement, pozzolana portland",
    "Cement, type ip",
    "Cement, cem ii/b",
    "Cement, cp ii-f",
  ],
  "Cereals (except rice), leguminous crops and oil seeds": [
    "Soybean, swiss integrated production",
    "Sweet sorghum grain",
    "Oat grain",
    "Protein pea",
    "Protein pea, swiss integrated production",
    "Rape seed",
    "Sunflower seed, swiss integrated production",
    "Maize grain, organic",
    "Sunflower seed",
    "Peanut",
    "Rape seed, organic",
    "Barley grain, swiss integrated production",
    "Jatropha seed",
    "Linseed",
    "Soybean, organic",
    "Mustard",
    "Sweet corn",
    "Fava bean, swiss integrated production",
    "Straw",
    "Rape seed, swiss integrated production",
    "Wheat grain, swiss integrated production",
    "Linseed seed, at farm",
    "Fava bean",
    "Wheat grain",
    "Sesame seed",
    "Sweet sorghum stem",
    "Chickpea",
    "Straw, organic",
    "Maize grain, swiss integrated production",
    "Straw, stand-alone production",
    "Rye grain",
    "Maize grain",
    "Maize seed, swiss integrated production, at farm",
    "Lentil",
    "Barley grain",
    "Maize seed, organic, at farm",
    "Rye grain, swiss integrated production",
    "Oat seed, swiss integrated production, at farm",
    "Maize seed, at farm",
    "Navy bean",
    "Soybean",
    "Red kidney bean",
    "Millet",
    "Fava bean, organic",
    "Protein pea, organic",
    "Wheat grain, organic",
    "Barley grain, organic",
    "Castor bean",
    "Pinto bean",
    "Peanut seed, at farm",
    "Rye grain, organic",
  ],
  "Chemical and fertilizer minerals": [
    "Fluorspar, 97% purity",
    "Stone meal",
    "Sodium borates",
    "Dolomite",
    "Boric acid, anhydrous, powder",
    "Intral",
    "Soil ph raising agent, as caco3",
    "Potash salt",
    "Purge gas, rich in sodium nitrate",
    "Phosphate rock, beneficiated",
    "Calcium borates",
  ],
  "Chemicals and chemical products": [
    "Flux, for wave soldering",
    "Electrolyte, for li-ion battery",
    "Explosive, tovex",
    "Solvent, organic",
    "Naphthalene sulfonic acid",
    "Octabenzone",
    "Spent activated carbon, granular",
    "Solder, paste, sn95.5ag3.9cu0.6, for electronics industry",
    "Metallization paste, back side",
    "Activated carbon, granular",
    "Polyurethane adhesive",
    "Melamine urea formaldehyde adhesive",
    "Rosin size, for paper production",
    "Brazing solder, cadmium free",
    "Nitrate salts, for solar power application",
    "Heavy water",
    "Adhesive, for metal",
    "Seal, natural rubber based",
    "Soft solder, sn97cu3",
    "Indium tin oxide powder, nanoscale, for sputtering target",
    "Solder, bar, sn95.5ag3.9cu0.6, for electronics industry",
    "Solder, bar, sn63pb37, for electronics industry",
    "Metallization paste, front side",
    "Solder, paste, sn63pb37, for electronics industry",
    "Metallization paste, back side, aluminium",
  ],
  "Citrus fruits": [
    "Orange, fresh grade",
    "Mandarin, fresh grade",
    "Mandarin",
    "Mandarin, processing grade",
    "Lemon",
    "Orange, processing grade",
  ],
  "Clay building materials": [
    "Light clay brick",
    "Cobwork",
    "Roof tile",
    "Ceramic tile",
    "Sanitary ceramics",
    "Clay plaster",
    "Shale brick",
    "Clay brick",
  ],
  "Coke oven products": ["Coal tar"],
  "Communication equipment": ["Chassis, internet access equipment"],
  "Computers and peripheral equipment": [
    "Cathode-ray tube, cathode ray tube display",
    "Backlight, for liquid crystal display",
    "Liquid crystal display, minor components, auxilliaries and assembly effort",
    "Assembly of liquid crystal display, auxilliaries and energy use",
  ],
  "Corrugated paper and paperboard": [
    "Liquid packaging board container",
    "Carton board box production, with gravure printing",
    "Carton board box production, with offset printing",
    "Containerboard, fluting medium",
    "Liquid packaging board",
    "Corrugated board box",
    "Containerboard, unspecified",
    "Paper sack",
    "Containerboard, linerboard",
  ],
  "Crude petroleum": [
    "Water discharge from petroleum extraction, offshore",
    "Water discharge from petroleum/natural gas extraction, onshore",
    "Petroleum combustion, in drilling tests",
  ],
  "Dairy products": [
    "Evaporation of milk",
    "Whey",
    "Skimmed milk, from cow milk",
    "Buttermilk, from cow milk",
    "Spray-drying of milk",
    "Yogurt, from cow milk",
    "Cream, from cow milk",
    "Butter, from cow milk",
    "Cheese, from cow milk, fresh, unripened",
  ],
  "Electric motors, generators, and transformers": [
    "Electric motor, for electric scooter",
    "Controller, for electric scooter",
    "Electric motor, vehicle",
    "Electric motor, electric passenger car",
    "Power distribution unit, for electric passenger car",
    "Powertrain, for electric scooter",
    "Transformer, high voltage use",
    "Electronics, for control units",
    "Transformer, low voltage use",
    "Powertrain, for electric passenger car",
  ],
  "Electric power generation, transmission and distribution": [
    "Sox retained, in hard coal flue gas desulfurisation",
    "Nox retained, by selective catalytic reduction",
    "N2o retained, by regenerative thermal oxidation",
    "Sox retained, in lignite flue gas desulfurisation",
  ],
  "Electronic components and boards": [
    "Electronic component, passive, unspecified",
    "Electric connector, peripheral component interconnect buss",
    "Printed wiring board, through-hole mounted, unspecified, pb containing",
    "Electronic component, passive, mobile, earpiece and speaker",
    "Electronic component, active, unspecified",
    "Printed wiring board, for power supply unit, desktop computer, pb containing",
    "Liquid crystal display, unmounted, mobile device",
    "Capacitor, electrolyte type, < 2cm height",
    "Capacitor, auxilliaries and energy use",
    "Potentiometer, unspecified",
    "Printed wiring board, surface mounted, unspecified, pb free",
    "Inductor, low value multilayer chip",
    "Transistor, wired, small size, through-hole mounting",
    "Diode, glass-, for through-hole mounting",
    "Resistor, auxilliaries and energy use",
    "Printed wiring board, mounted mainboard, desktop computer, pb free",
    "Capacitor, tantalum-, for through-hole mounting",
    "Cable, ribbon cable, 20-pin, with plugs",
    "Diode, glass-, for surface-mounting",
    "Diode, auxilliaries and energy use",
    "Printed wiring board, mounted mainboard, laptop computer, pb free",
    "Resistor, metal film type, through-hole mounting",
    "Inductor, miniature radio frequency chip",
    "Liquid crystal display, unmounted",
    "Transistor, wired, big size, through-hole mounting",
    "Insulated gate bipolar transistor, electric vehicle application",
    "Printed wiring board, through-hole mounted, unspecified, pb free",
    "Electron gun, for cathode ray tube display",
    "Polarizer, liquid crystals and colour filters, for liquid crystal display",
    "Printed wiring board, surface mounted, unspecified, pb containing",
    "Integrated circuit, memory type",
    "Inductor, auxilliaries and energy use",
    "Integrated circuit, logic type",
    "Transistor, auxilliaries and energy use",
    "Capacitor, electrolyte type, > 2cm height",
    "Printed wiring board, for power supply unit, desktop computer, pb free",
    "Resistor, wirewound, through-hole mounting",
    "Transistor, surface-mounted",
    "Fan, for power supply unit, desktop computer",
    "Resistor, surface-mounted",
    "Electric connector, peripheral type buss",
    "Switch, toggle type",
    "Light emitting diode",
    "Inductor, ring core choke type",
    "Capacitor, film type, for through-hole mounting",
    "Capacitor, for surface-mounting",
    "Printed wiring board, mounted mainboard, laptop computer, pb containing",
    "Printed wiring board, mounted mainboard, desktop computer, pb containing",
    "Electric connector, wire clamp",
  ],
  "Fabricated metal products": [
    "Permanent magnet, for electric motor",
    "Energy and auxilliary inputs, metal working factory",
    "Metal working, average for chromium steel product manufacturing",
    "Metal working, average for metal product manufacturing",
    "Metal working, average for copper product manufacturing",
    "Energy and auxilliary inputs, metal working machine",
    "Metal working, average for aluminium product manufacturing",
    "Metal working, average for steel product manufacturing",
  ],
  "Fertilizers and nitrogen compounds": [
    "Ammonia, anhydrous, liquid",
    "Potassium nitrate, industrial grade",
    "Sulfuric acid",
    "Npk (15-15-15) fertiliser",
    "Potassium chloride",
    "Triple superphosphate",
    "Ammonium bicarbonate",
    "Calcium ammonium nitrate",
    "Urea",
    "Ammonium nitrate",
    "Potassium nitrate",
    "Diammonium phosphate",
    "Single superphosphate",
    "Fluosilicic acid, without water, in 22% solution state",
    "Monoammonium phosphate",
    "Calcium nitrate",
    "Npk (26-15-15) fertiliser",
    "Urea ammonium nitrate mix",
    "Carbon dioxide, in chemical industry",
    "Sodium nitrate, technical grade",
    "Potassium sulfate",
    "Nitric acid, without water, in 50% solution state",
    "Phosphoric acid, fertiliser grade, without water, in 70% solution state",
    "Ammonium carbonate",
    "Sodium nitrate, unrefined",
    "Lime, from liquid packaging board production",
    "Potassium nitrate, technical grade",
    "Ammonium nitrate phosphate",
    "Potassium nitrate, agricultural grade",
    "Ammonium sulfate",
    "Potassium chloride, industrial grade",
  ],
  "Fibre crops": [
    "Flax plant, harvested",
    "Seed-cotton",
    "Sunn hemp plant, harvested",
    "Jute plant, harvested",
    "Seed-cotton, organic",
    "Kenaf plant, harvested",
  ],
  "Fish, crustaceans and molluscs": [
    "Fish curing, small fish",
    "Fish canning, small fish",
    "Fish residues",
    "Fish freezing, small fish",
    "Fishmeal, 63-65% protein",
    "Fishmeal, 65-67% protein",
    "Fish oil, from anchovy",
    "Fish canning, large fish",
  ],
  "Freshwater aquaculture": ["Trout", "Tilapia"],
  "Fruit and vegetables": [
    "Tofu",
    "Palm date, conditioned and dried, organic",
    "Palm date, conditioned and dried",
  ],
  Furniture: ["Furniture, wooden"],
  "Gas; distribution of gaseous fuels through mains": [
    "Natural gas, low pressure, vehicle grade",
    "Natural gas, medium pressure, vehicle grade",
    "Natural gas liquids",
    "Biomethane, medium pressure, vehicle grade",
    "Helium, crude",
    "Natural gas, high pressure, vehicle grade",
    "Biomethane, low pressure, vehicle grade",
    "Biomethane, high pressure, vehicle grade",
  ],
  "Glass and glass products": [
    "Glass, for liquid crystal display",
    "Glass fibre",
    "Flat glass, coated",
    "Solar collector glass tube, with silver mirror",
    "Frit, for cathode ray tube display",
    "Panel glass, for cathode ray tube display",
    "Funnel glass, for cathode ray tube display",
    "Packaging glass, brown",
    "Tempering, flat glass",
    "Solar glass, low-iron",
    "Packaging glass, white",
    "Flat glass, uncoated",
    "Glass tube, borosilicate",
    "Packaging glass, green",
  ],
  "Grain mill products": [
    "Wheat flour mix",
    "Maize chop",
    "Wheat bran",
    "Maize flour",
    "Wheat flour",
    "Breadcrumbs",
  ],
  Grapes: ["Grape"],
  "Hard coal": ["Hard coal", "Hard coal, run-of-mine"],
  "Hazardous waste": [
    "Non-sulfidic overburden, off-site",
    "Green liquor dregs",
    "Used refrigerant r-600a",
    "Spent solvent mixture",
    "Spent formox catalyst base from formaldehyde production",
    "Sulfidic tailings, from nickel mine operation",
    "Waste cement, hydrated",
    "Zinc slag",
    "Refinery sludge",
    "Hazardous waste, for underground deposit",
    "Ash from deinking sludge",
    "Sulfidic tailings, from zinc-lead mine operation",
    "Spent antifreezer liquid",
    "Used perfluoropentane",
    "Average incineration residue",
    "Hazardous waste, for incineration",
    "Waste mineral oil",
    "Lead smelter slag",
    "Residue from na-dichromate production",
    "Tin slag",
    "Spent pot liner from al electrolysis, carbon fraction",
    "Filter dust from al electrolysis",
    "Process-specific burdens, hazardous waste incineration plant",
    "Sulfidic tailings, generic",
    "Basic oxygen furnace waste",
    "Sulfidic tailings, from copper mine operation",
    "Redmud from bauxite digestion",
    "Fly ash and scrubber sludge",
    "Spoil from hard coal mining",
    "Antimony slag, desulfurised",
    "Process-specific burdens, residual material landfill",
    "Ash from paper production sludge",
    "Used refrigerant r-12",
    "Copper slag",
    "Antimony slag, water-quenched",
    "Sulfidic tailings, from gold mine operation",
    "Used refrigerant r134a",
    "Spent nuclear fuel",
    "Used capacitor",
    "Sulfidic tailings, from cinnabar mine operation",
    "H3po4 purification residue",
    "Salt tailing from potash mine",
    "Residue from rutile production, synthetic, 56% water",
    "Coal slurry",
    "Dross from al electrolysis",
    "Non-sulfidic tailing, off-site",
    "Residue from tio2 production, chloride process",
    "Bilge oil",
    "Refractory spent pot liner from al electrolysis",
    "Sludge, nacl electrolysis hg",
    "Decarbonising waste",
    "Residue from tio2 production, sulfate process",
    "Spent catalyst base from ethyleneoxide production",
    "Sulfidic tailings, from silver mine operation",
    "Waste frit from cathode ray tube production",
    "Sludge, nacl electrolysis",
    "Pollutant from rail ballast",
    "Sludge from steel rolling",
    "Nickel smelter slag",
    "Waste, from silicon wafer production, inorganic",
    "Spoil from lignite mining",
  ],
  "Iron and steel": ["Casting, steel, lost-wax"],
  "Iron ores": [
    "Iron ore concentrate",
    "Portafer",
    "Iron ore, crude ore, 46% fe",
    "Iron ore, crude ore, 63% fe",
  ],
  "Knitted and crocheted fabrics": ["Textile, knit cotton"],
  Lignite: ["Lignite"],
  Logging: [
    "Cleft timber, measured as dry mass",
    "Charcoal",
    "Wood chips, wet, measured as dry mass",
    "Bundle, energy wood, measured as dry mass",
  ],
  "Machinery for mining, quarrying and construction": [
    "Rock crushing",
    "Industrial machine, heavy, unspecified",
  ],
  "Man-made fibres": ["Fibre, polyester", "Silky fibre", "Fibre, viscose"],
  "Marine fishing": [
    "Purse seiner maintenance, steel",
    "Used purse seiner, steel",
    "Used trawler, steel",
    "Purse seiner, wood",
    "Trawler, steel",
    "Landed tuna, frozen, epo",
    "Purse seiner maintenance, wood",
    "Landed anchovy, fresh",
    "Small pelagic fish, fresh",
    "Long liner, steel",
    "Fish block, hake",
    "Used long liner, steel",
    "Trawler maintenance, steel",
    "Landed anchovy by-catch, fresh",
    "Used purse seiner, wood",
    "Landed hake, fresh",
    "Long liner maintenance, steel",
    "Antifouling paint emissions",
    "Demersal fish, fresh",
    "Purse seiner, steel",
    "Marine fish",
  ],
  "Materials recovery": [
    "Waste paint on metal",
    "Waste plaster-cardboard sandwich",
    "Waste reinforced concrete",
    "Aluminium scrap, post-consumer",
    "Zinc scrap, post-consumer",
    "Used printer, laser",
    "Wood chips, from post-consumer wood, measured as dry mass",
    "Decommissioned chemical production facilities",
    "Glass cullet, sorted",
    "Polyethylene terephthalate, granulate, bottle grade, recycled",
    "Used printed wiring boards",
    "Used smartphone",
    "Iron scrap, unsorted",
    "Used glider, electric scooter",
    "Electronics scrap from control units",
    "Tinplate, in mixed metal scrap",
    "Waste electric and electronic equipment",
    "Used ni-metal hydride battery",
    "Ferrous metal, in mixed metal scrap",
    "Used powertrain, electric scooter",
    "Bronze scrap, post-consumer",
    "Aluminium scrap, post-consumer, prepared for melting",
    "Used laptop computer",
    "Used vegetable cooking oil, purified",
    "Waste packaging glass, unsorted",
    "Waste x-ray film",
    "Iron scrap, sorted, pressed",
    "Used desktop computer",
    "Used powertrain from electric passenger car, manual dismantling",
    "Waste reinforced plasterboard",
    "Waste wood, post-consumer",
    "Used beverage cans",
    "Used vegetable cooking oil",
    "Polyethylene terephthalate, granulate, amorphous, recycled",
    "Waste paperboard, unsorted",
    "Waste plastic, consumer electronics, sorted",
    "Shredder fraction after manual dismantling of used electronic product",
    "Waste paper, unsorted",
    "Waste bulk iron, excluding reinforcement",
    "Aluminium, in mixed metal scrap",
    "Plastic granulate, unspecified, recycled",
    "Used it accessory",
    "Waste gypsum plasterboard",
    "Plastic flake, consumer electronics, for recycling",
    "Used glider, passenger car",
    "Used cathode ray tube display",
    "Glass from used cathode ray tube",
    "Waste concrete gravel",
    "Used liquid crystal display",
    "Waste paperboard, sorted",
    "Used fluorescent lamp",
    "Used internal combustion engine, passenger car",
    "Polyethylene, high density, granulate, recycled",
    "Waste concrete, not reinforced",
    "Waste paper, sorted",
    "Waste brick",
    "Used li-ion battery",
    "Waste mineral wool",
    "Used industrial electronic device",
    "Waste reinforcement steel",
    "Tinplate scrap, sorted",
    "Used tablet",
    "Used cable",
  ],
  Meat: ["Meat and bone meal", "Horn meal", "Slaughterhouse waste"],
  "Metal-forming machinery and machine tools": [
    "Metal working machine, unspecified",
  ],
  "Metal; powder metallurgy": [
    "Impact extrusion of steel, warm, 4 strokes",
    "Deep drawing, steel, 650 kn press, single stroke",
    "Impact extrusion of aluminium, 4 strokes",
    "Impact extrusion of steel, cold, deformation stroke",
    "Impact extrusion of steel, warm, deformation stroke",
    "Impact extrusion of steel, hot, deformation stroke",
    "Impact extrusion of steel, cold, 4 strokes",
    "Impact extrusion of steel, hot, 3 strokes",
    "Deep drawing, steel, 10000 kn press, single stroke",
    "Impact extrusion of steel, hot, 1 strokes",
    "Impact extrusion of aluminium, 1 stroke",
    "Impact extrusion of aluminium, cold, tempering",
    "Impact extrusion of steel, warm, 5 strokes",
    "Deep drawing, steel, 10000 kn press, automode",
    "Impact extrusion of steel, hot, initial warming",
    "Impact extrusion of steel, warm, 3 strokes",
    "Impact extrusion of steel, warm, 1 strokes",
    "Impact extrusion of aluminium, deformation stroke",
    "Impact extrusion of aluminium, cold, initial surface treatment",
    "Impact extrusion of steel, hot, 5 strokes",
    "Impact extrusion of steel, cold, tempering",
    "Impact extrusion of steel, cold, 2 strokes",
    "Deep drawing, steel, 38000 kn press, automode",
    "Impact extrusion of steel, cold, 3 strokes",
    "Deep drawing, steel, 38000 kn press, single stroke",
    "Deep drawing, steel, 650 kn press, automode",
    "Impact extrusion of aluminium, 5 strokes",
    "Deep drawing, steel, 3500 kn press, automode",
    "Impact extrusion of aluminium, 3 strokes",
    "Impact extrusion of aluminium, 2 strokes",
    "Impact extrusion of steel, cold, 1 strokes",
    "Impact extrusion of steel, cold, 5 strokes",
    "Deep drawing, steel, 3500 kn press, single stroke",
    "Impact extrusion of steel, hot, 2 strokes",
    "Impact extrusion of steel, hot, tempering",
    "Impact extrusion of steel, cold, initial surface treatment",
    "Impact extrusion of steel, warm, 2 strokes",
    "Impact extrusion of steel, warm, initial warming",
    "Impact extrusion of steel, hot, 4 strokes",
  ],
  "Metals; machining": [
    "Aluminium removed by milling, large parts",
    "Cast iron removed by turning, primarily roughing, conventional",
    "Steel removed by milling, average",
    "Cast iron removed by drilling, conventional",
    "Chromium steel removed by turning, primarily dressing, computer numerical controlled",
    "Cast iron removed by turning, primarily dressing, computer numerical controlled",
    "Steel removed by drilling, computer numerical controlled",
    "Brass removed by drilling, computer numerical controlled",
    "Contouring, bronze",
    "Chromium steel removed by turning, average, conventional",
    "Cast iron removed by drilling, computer numerical controlled",
    "Steel removed by milling, large parts",
    "Aluminium removed by turning, average, conventional",
    "Aluminium removed by milling, dressing",
    "Chromium steel removed by turning, average, computer numerical controlled",
    "Chromium steel removed by turning, primarily dressing, conventional",
    "Steel removed by milling, dressing",
    "Brass removed by turning, primarily dressing, computer numerical controlled",
    "Cast iron removed by turning, primarily dressing, conventional",
    "Cast iron removed by turning, primarily roughing, computer numerical controlled",
    "Sputtering target, sintered, indium tin oxide",
    "Steel removed by turning, primarily roughing, conventional",
    "Chromium steel removed by milling, average",
    "Chromium steel removed by milling, dressing",
    "Chromium steel removed by turning, primarily roughing, computer numerical controlled",
    "Steel removed by turning, primarily dressing, computer numerical controlled",
    "Steel removed by turning, average, conventional",
    "Cast iron removed by milling, average",
    "Brass removed by turning, average, computer numerical controlled",
    "Cast iron removed by turning, average, conventional",
    "Steel removed by turning, primarily dressing, conventional",
    "Brass removed by turning, average, conventional",
    "Aluminium removed by turning, primarily dressing, computer numerical controlled",
    "Chromium steel removed by drilling, conventional",
    "Aluminium removed by milling, average",
    "Cast iron removed by milling, dressing",
    "Aluminium removed by turning, primarily dressing, conventional",
    "Chromium steel removed by milling, small parts",
    "Cast iron removed by milling, large parts",
    "Steel removed by milling, small parts",
    "Steel removed by turning, average, computer numerical controlled",
    "Contouring, brass",
    "Steel removed by turning, primarily roughing, computer numerical controlled",
    "Cast iron removed by turning, average, computer numerical controlled",
    "Brass removed by drilling, conventional",
    "Aluminium removed by drilling, computer numerical controlled",
    "Aluminium removed by drilling, conventional",
    "Aluminium removed by turning, primarily roughing, computer numerical controlled",
    "Aluminium removed by turning, average, computer numerical controlled",
    "Brass removed by turning, primarily dressing, conventional",
    "Aluminium removed by milling, small parts",
    "Aluminium removed by turning, primarily roughing, conventional",
    "Chromium steel removed by drilling, computer numerical controlled",
    "Brass removed by turning, primarily roughing, conventional",
    "Brass removed by turning, primarily roughing, computer numerical controlled",
    "Chromium steel removed by turning, primarily roughing, conventional",
    "Chromium steel removed by milling, large parts",
    "Steel removed by drilling, conventional",
    "Cast iron removed by milling, small parts",
  ],
  "Mining and quarrying": ["Asbestos, crysotile type", "Graphite"],
  "Motor vehicles": [
    "Passenger car, diesel",
    "Internal combustion engine, passenger car",
    "Passenger car, petrol/natural gas",
    "Glider, passenger car",
    "Passenger car, electric, without battery",
  ],
  Motorcycles: [
    "Electric scooter, without battery",
    "Glider, for electric scooter",
  ],
  "Natural gas": ["Sulfur"],
  "Non-ferrous metals": [
    "Casting, brass",
    "Casting, bronze",
    "Tin",
    "Casting, aluminium, lost-wax",
  ],
  "Non-hazardous waste": [
    "Waste mineral wool, for final disposal",
    "Basic oxygen furnace slag",
    "Waste plastic plaster, for final disposal",
    "Sewage sludge, 97% water, wwt, ww from tube collector production",
    "Sewage sludge, 75% water, wwt, ww from potato starch production",
    "Sewage sludge, 70% water, wwt, ww from potato starch production",
    "Waste plastic, consumer electronics",
    "Waste mineral plaster",
    "Basic oxygen furnace dust, for recovery",
    "Waste rubber, unspecified",
    "Sewage sludge, 75% water, wwt, ww from ceramic production",
    "Sewage sludge, 97% water, wwt, ww from concrete production",
    "Process-specific burdens, municipal waste incineration",
    "Residues, mswi[f]-wwt, ww from concrete production",
    "Residues, mswi[f]-wwt, ww from tube collector production",
    "Residues, mswi-wwt, condensate from light oil boiler",
    "Waste bitumen",
    "Waste plastic, mixture",
    "Sewage sludge, 70% water, wwt, ww from hard fibreboard production",
    "Bottom ash, mswi-wwt, ww from crt production",
    "Bottom ash, mswi-wwt, ww from lcd backlight production",
    "Tyre wear emissions, passenger car",
    "Residues, mswi[f]-wwt[u], ww from lorry production",
    "Blast furnace dust, for recovery",
    "Sewage sludge, 70% water, wwt, ww from lcd production",
    "Waste wood, untreated",
    "Residues, mswi[f]-wwt, ww from ceramic production",
    "Waste bamboo residues",
    "Residue from mechanical treatment, desktop computer",
    "Sewage sludge, 97% water, wwt, ww from wafer fabrication",
    "Basic oxygen furnace dust",
    "Sewage sludge, 70% water, wwt, ww from glass production",
    "Sewage sludge, 75% water, wwt, ww from lcd backlight production",
    "Sewage sludge, 70% water, wwt, ww from crt production",
    "Bottom ash, mswi-wwt, ww from particle board production",
    "Waste newspaper",
    "Road wear emissions, lorry",
    "Sewage sludge, 70% water, wwt, ww from concrete production",
    "Blast furnace slag",
    "Residues, mswi-wwt, ww from ammonium paratungstate production",
    "Residue from mechanical treatment, laptop computer",
    "Bottom ash, mswi-wwt, ww from vegetable oil refinery",
    "Residues, mswi[f]-wwt, ww from glass production",
    "Sewage sludge, 75% water, wwt[u], ww from lorry production",
    "Bottom ash, mswi-wwt, ww from wafer fabrication",
    "Waste building wood, chrome preserved",
    "Zinc in car shredder residue",
    "Sewage sludge, 97% water, wwt, ww from medium density board production",
    "Waste yarn and waste textile",
    "Drilling waste",
    "Waste fibreboard",
    "Residues, mswi[f]-wwt, ww from soft fibreboard production",
    "Sewage sludge, 75% water, wwt, heat carrier liquid, 40% c3h8o2",
    "Waste emulsion paint, on wood",
    "Aluminium in car shredder residue",
    "Bottom ash, mswi[f]-wwt, ww from grass refinery",
    "Waste cement in concrete and mortar",
    "Residues, mswi-wwt, ww, average",
    "Bottom ash, mswi[f]-wwt, ww from potato starch production",
    "Bottom ash, mswi-wwt, ww from tube collector production",
    "Sewage sludge, 75% water, wwt, ww, average",
    "Residue from mechanical treatment, cathode ray tube display",
    "Limestone residue",
    "Waste paint on wood",
    "Bottom ash, mswi[f]-wwt, ww from lcd production",
    "Residues, mswi-wwt, ww from medium density board production",
    "Sewage sludge, 75% water, wwt, ww from maize starch production",
    "Bottom ash, mswi[f]-wwt, ww from ceramic production",
    "Sewage sludge, 70% water, wwt, ww from particle board production",
    "Residues, mswi-wwt, heat carrier liquid, 40% c3h8o2",
    "Waste packaging paper",
    "Spent cation exchange resin from potable water production",
    "Waste polyvinylchloride",
    "Bottom ash, mswi-wwt, ww from ammonium paratungstate production",
    "Wood ash mixture, pure",
    "Waste sealing sheet, polyvinylchloride",
    "Sewage sludge, 70% water, wwt[r], ww from anaerobic digestion of whey",
    "Bottom ash, mswi-wwt, ww from medium density board production",
    "Steel in car shredder residue",
    "Bottom ash, mswi-wwt[r], ww from anaerobic digestion of whey",
    "Residues, mswi-wwt, ww from pv cell production",
    "Residues, mswi-wwt[r], ww from anaerobic digestion of whey",
    "Bottom ash, mswi-wwt, ww from ceramic production",
    "Waste textile, soiled",
    "Sewage sludge, 70% water, wwt, ww from ggbfs production",
    "Bottom ash, mswi[f]-wwt, rainwater mineral oil storage",
    "Biowaste",
    "Electric arc furnace dust",
    "Sewage sludge, 70% water, wwt, ww from black chrome coating",
    "Waste polyethylene terephthalate, for recycling, sorted",
    "Sewage sludge, 70% water, wwt, ww, average",
    "Biowaste, kitchen and garden waste",
    "Waste polyethylene terephthalate",
    "Sewage sludge, 97% water, wwt, ww from pv cell production",
    "Residues, mswi-wwt, ww from tube collector production",
    "Sewage sludge, 97% water, wwt, ww from lcd backlight production",
    "Used liquid crystal display module",
    "Sewage sludge, 70% water, wwt, ww from wafer fabrication",
    "Waste cement-fibre slab, dismantled",
    "Bottom ash, mswi[f]-wwt, ww from plywood production",
    "Residues, mswi[f]-wwt[r], ww from anaerobic digestion of whey",
    "Residues, mswi-wwt, ww from liquid crystal production",
    "Waste paint on wall",
    "Sewage sludge, 75% water, wwt, ww from glass production",
    "Waste emulsion paint, separated",
    "Scrap steel",
    "Sewage sludge, 97% water, wwt, ww from soft fibreboard production",
    "Sewage sludge, 97% water, wwt[u], ww from lorry production",
    "Bottom ash, mswi-wwt, ww from maize starch production",
    "Residues, mswi[f]-wwt, ww from lcd production",
    "Sewage sludge, 75% water, wwt, ww from black chrome coating",
    "Waste polyvinylchloride product",
    "Sewage sludge, 70% water, wwt, ww from pv cell production",
    "Waste, from silicon wafer production",
    "Sewage sludge, 97% water, wwt, ww from particle board production",
    "Residues, mswi-wwt, ww from hard fibreboard production",
    "Bottom ash, mswi-wwt[u], ww from lorry production",
    "Residues, mswi-wwt, ww from crt production",
    "Residues, mswi-wwt, ww from wafer fabrication",
    "Sewage sludge, 70% water, wwt, ww from maize starch production",
    "Residue from shredder fraction from manual dismantling",
    "Residues, mswi[f]-wwt, ww from potato starch production",
    "Waste polystyrene",
    "Residues, mswi[f]-wwt, ww from maize starch production",
    "Sewage sludge, 70% water, wwt, condensate from light oil boiler",
    "Bottom ash, mswi[f]-wwt, ww from crt production",
    "Sewage sludge, 70% water, wwt, ww from tube collector production",
    "Sewage sludge, 70% water, wwt[u], ww from lorry production",
    "Sewage sludge, 97% water, wwt, ww from plywood production",
    "Slag from metallurgical grade silicon production",
    "Bottom ash, mswi-wwt, ww from glass production",
    "Waste glass sheet",
    "Metalliferous hydroxide sludge",
    "Sewage sludge, 97% water, wwt, ww from ammonium paratungstate production",
    "Spent catalytic converter for cars",
    "Waste vapour barrier, flame-retarded",
    "Sewage sludge, 75% water, wwt, condensate from light oil boiler",
    "Sewage sludge, 75% water, wwt, ww from plywood production",
    "Glass cullet, from fluorescent lamps treatment",
    "Bottom ash, mswi-wwt, ww from potato starch production",
    "Sewage sludge, 97% water, wwt, ww from black chrome coating",
    "Blast furnace sludge, for recovery",
    "Waste polypropylene",
    "Raw sewage sludge",
    "Basic oxygen furnace sludge, for recovery",
    "Bottom ash, mswi-wwt, ww from ggbfs production",
    "Bottom ash, mswi-wwt, heat carrier liquid, 40% c3h8o2",
    "Brake wear emissions, passenger car",
    "Sewage sludge, 70% water, wwt, ww from grass refinery",
    "Sewage sludge, 97% water, wwt, ww from maize starch production",
    "Waste polyethylene/polypropylene product",
    "Bottom ash, mswi-wwt, rainwater mineral oil storage",
    "Residues, mswi[f]-wwt, ww, average",
    "Waste glass",
    "Residues, mswi-wwt, ww from vegetable oil refinery",
    "Waste paperboard",
    "Waste mixed aggregates, from demolition",
    "Sewage sludge, 97% water, wwt, ww from ggbfs production",
    "Residues, mswi[f]-wwt, ww from pig iron production",
    "Copper in car shredder residue",
    "Bottom ash, mswi-wwt, ww from hard fibreboard production",
    "Residue from mechanical treatment, liquid crystal display",
    "Sewage sludge, 75% water, wwt, ww from soft fibreboard production",
    "Road wear emissions, passenger car",
    "Waste concrete",
    "Lead in car shredder residue",
    "Bottom ash, mswi[f]-wwt, ww from tube collector production",
    "Bottom ash, mswi-wwt, ww from black chrome coating",
    "Blast furnace sludge",
    "Municipal solid waste",
    "Sewage sludge, 97% water, wwt, ww from lcd production",
    "Waste expanded polystyrene",
    "Residues, mswi-wwt, ww from maize starch production",
    "Bottom ash, mswi[f]-wwt[u], ww from lorry production",
    "Sewage sludge, 70% water, wwt, rainwater mineral oil storage",
    "Bottom ash, mswi[f]-wwt, ww from concrete production",
    "Process-specific burdens, inert material landfill",
    "Glass cullet, for saint-gobain isover sa",
    "Digester sludge",
    "Coating from waste cathode ray tube display",
    "Lignite ash",
    "Sewage sludge, 70% water, wwt, ww from lcd backlight production",
    "Waste asphalt",
    "Basic oxygen furnace slag, for recovery",
    "Basic oxygen furnace secondary metallurgy slag",
    "Residues, mswi-wwt, ww from ggbfs production",
    "Sewage sludge, 97% water, wwt, ww from hard fibreboard production",
    "Residue from mechanical treatment, laser printer",
    "Bottom ash, mswi-wwt, ww from plywood production",
    "Inert waste, for final disposal",
    "Sewage sludge, 97% water, wwt, ww from ceramic production",
    "Bottom ash, mswi[f]-wwt, ww from glass production",
    "Bottom ash, mswi-wwt, ww from soft fibreboard production",
    "Waste emulsion paint, on wall",
    "Residues, mswi-wwt, ww from pig iron production",
    "Waste emulsion paint",
    "Residues, mswi[f]-wwt, condensate from light oil boiler",
    "Residues, mswi[f]-wwt, ww from grass refinery",
    "Biowaste, garden waste",
    "Mill scale",
    "Sewage sludge, 75% water, wwt, ww from concrete production",
    "Process-specific burdens, slag landfill",
    "Waste polyethylene, for recycling, sorted",
    "Waste polyurethane",
    "Spent activated carbon with mercury",
    "Waste polyethylene, for recycling, unsorted",
    "Waste wire plastic",
    "Sewage sludge, 97% water, wwt, ww from liquid crystal production",
    "Residues, mswi-wwt, ww from ceramic production",
    "Waste glass pane in burnable frame",
    "Scrap copper",
    "Sewage sludge, 75% water, wwt, ww from ggbfs production",
    "Waste plastic plaster",
    "Sewage sludge, 75% water, wwt, ww from vegetable oil refinery",
    "Waste, electrical and electronic cables",
    "Residues, mswi-wwt, ww from lcd production",
    "Sludge from fecl3 production",
    "Sewage sludge, 75% water, wwt, ww from tube collector production",
    "Poultry manure, dried",
    "Waste polyethylene terephthalate, for recycling, unsorted",
    "Sewage sludge, 70% water, wwt, ww from soft fibreboard production",
    "Basic oxygen furnace sludge",
    "Sewage sludge, 97% water, wwt, ww, average",
    "Bottom ash, mswi[f]-wwt[r], ww from anaerobic digestion of whey",
    "Spent anion exchange resin from potable water production",
    "Waste plastic, industrial electronics",
    "Blast furnace dust",
    "Scrap tin sheet",
    "Bottom ash, mswi[f]-wwt, ww from soft fibreboard production",
    "Residues, mswi[f]-wwt, rainwater mineral oil storage",
    "Waste plastic, consumer electronics, unsorted",
    "Sewage sludge, 75% water, wwt, ww from lcd production",
    "Bottom ash, mswi-wwt, ww from pig iron production",
    "Sewage sludge, 97% water, wwt[r], ww from anaerobic digestion of whey",
    "Waste electric wiring",
    "Compost",
    "Bottom ash, mswi-wwt, ww from lcd production",
    "Sewage sludge, 75% water, wwt, rainwater mineral oil storage",
    "Residues, mswi-wwt, ww from particle board production",
    "Scrap aluminium",
    "Electric arc furnace secondary metallurgy slag",
    "Bottom ash, mswi[f]-wwt, heat carrier liquid, 40% c3h8o2",
    "Bottom ash, mswi-wwt, ww, average",
    "Sewage sludge, 75% water, wwt, ww from hard fibreboard production",
    "Residue from cooling tower",
    "Glass cullet, from used cathode ray tube panels",
    "Sewage sludge, 75% water, wwt, ww from grass refinery",
    "Waste polystyrene isolation, flame-retardant",
    "Residues, mswi-wwt, ww from grass refinery",
    "Waste aluminium",
    "Bottom ash, mswi-wwt, ww from concrete production",
    "Sewage sludge, 75% water, wwt, ww from ammonium paratungstate production",
    "Sewage sludge, 70% water, wwt, ww from ammonium paratungstate production",
    "Bottom ash, mswi[f]-wwt, ww from maize starch production",
    "Used tyre",
    "Bottom ash, mswi-wwt, condensate from light oil boiler",
    "Decommissioned pipeline, natural gas",
    "Residues, mswi[f]-wwt, heat carrier liquid, 40% c3h8o2",
    "Residues, mswi[f]-wwt, ww from wafer fabrication",
    "Tyre wear emissions, lorry",
    "Glass cullet, lead containing, from used cathode ray tube",
    "Waste zeolite",
    "Sewage sludge, 70% water, wwt, ww from plywood production",
    "Sewage sludge, 97% water, wwt, heat carrier liquid, 40% c3h8o2",
    "Sewage sludge, 75% water, wwt, ww from pig iron production",
    "Residue from mechanical treatment, it accessory",
    "Sewage sludge, 97% water, wwt, ww from grass refinery",
    "Waste, pneumatic tyres",
    "Residue from mechanical treatment, industrial device",
    "Waste sealing sheet, polyethylene",
    "Residues, mswi[f]-wwt, ww from plywood production",
    "Sewage sludge, 75% water, wwt, ww from liquid crystal production",
    "Residues, mswi-wwt, ww from potato starch production",
    "Sewage sludge, 70% water, wwt, ww from pig iron production",
    "Sewage sludge, 75% water, wwt, ww from particle board production",
    "Bottom ash, mswi[f]-wwt, ww from pig iron production",
    "Residues, mswi-wwt[u], ww from lorry production",
    "Sewage sludge, 97% water, wwt, ww from pig iron production",
    "Bottom ash, mswi[f]-wwt, ww from pv cell production",
    "Sewage sludge, 75% water, wwt, ww from crt production",
    "Bottom ash, mswi-wwt, ww from grass refinery",
    "Bottom ash, mswi[f]-wwt, condensate from light oil boiler",
    "Bottom ash, mswi[f]-wwt, ww, average",
    "Sewage sludge, 70% water, wwt, heat carrier liquid, 40% c3h8o2",
    "Waste polyurethane foam",
    "Bottom ash, mswi[f]-wwt, ww from black chrome coating",
    "Waste gypsum",
    "Residues, mswi-wwt, ww from glass production",
    "Waste polyvinylfluoride",
    "Residues, mswi-wwt, ww from soft fibreboard production",
    "Residues, mswi-wwt, ww from black chrome coating",
    "Sewage sludge, 70% water, wwt, ww from medium density board production",
    "Brake wear emissions, lorry",
    "Residues, mswi-wwt, ww from lcd backlight production",
    "Sewage sludge, 97% water, wwt, rainwater mineral oil storage",
    "Sewage sludge, 70% water, wwt, ww from vegetable oil refinery",
    "Bottom ash, mswi-wwt, ww from pv cell production",
    "Bottom ash, mswi[f]-wwt, ww from wafer fabrication",
    "Sewage sludge, 97% water, wwt, ww from crt production",
    "Waste polyurethane seal",
    "Waste cement-fibre slab",
    "Sewage sludge, 97% water, wwt, ww from vegetable oil refinery",
    "Sewage sludge, 70% water, wwt, ww from ceramic production",
    "Residues, mswi[f]-wwt, ww from lcd backlight production",
    "Fibre and fabric waste, polyester",
    "Residues, mswi[f]-wwt, ww from black chrome coating",
    "Waste graphical paper",
    "Process-specific burdens, sanitary landfill",
    "Sewage sludge, 75% water, wwt, ww from medium density board production",
    "Sewage sludge, 97% water, wwt, ww from potato starch production",
    "Waste paint",
    "Bottom ash, mswi-wwt, ww from liquid crystal production",
    "Residues, mswi[f]-wwt, ww from liquid crystal production",
    "Waste bitumen sheet",
    "Electric arc furnace slag",
    "Residues, mswi-wwt, ww from plywood production",
    "Residues, mswi-wwt, ww from concrete production",
    "Sewage sludge, 97% water, wwt, ww from glass production",
    "Sewage sludge, 70% water, wwt, ww from liquid crystal production",
    "Sewage sludge, 75% water, wwt, ww from pv cell production",
    "Residues, mswi[f]-wwt, ww from crt production",
    "Residues, mswi[f]-wwt, ww from pv cell production",
    "Bottom ash, mswi[f]-wwt, ww from lcd backlight production",
    "Basic oxygen furnace secondary metallurgy slag, for recovery",
    "Sewage sludge, 97% water, wwt, condensate from light oil boiler",
    "Waste polyethylene",
    "Glass cullet, mixed glass from used cathode ray tube",
    "Sewage sludge, 75% water, wwt[r], ww from anaerobic digestion of whey",
    "Sludge from pulp and paper production",
    "Hard coal ash",
    "Residues, mswi-wwt, rainwater mineral oil storage",
    "Bottom ash, mswi[f]-wwt, ww from liquid crystal production",
    "Sewage sludge, 75% water, wwt, ww from wafer fabrication",
    "Waste wood pole, chrome preserved",
  ],
  "Non-metallic mineral products": [
    "Expanded clay",
    "Expanded vermiculite",
    "Lightweight concrete block, polystyrene",
    "Burnt shale",
    "Glass wool mat, uncoated, saint-gobain isover sa",
    "Glass wool mat",
    "Foam glass, electricity from renewable energy products",
    "Bitumen seal, va4",
    "Bitumen seal, polymer ep4 flame retardant",
    "Stone wool",
    "Lightweight concrete block, expanded clay",
    "Ground granulated blast furnace slag",
    "Bitumen seal, v60",
    "Mastic asphalt",
    "Bitumen seal, alu80",
    "Lightweight concrete block, expanded vermiculite",
    "Bitumen adhesive compound, cold",
    "Bitumen seal",
    "Lightweight concrete block, expanded perlite",
    "Calcined clay",
    "Stone wool, packed",
    "Foam glass",
    "Bitumen adhesive compound, hot",
    "Expanded perlite",
    "Lightweight concrete block, pumice",
  ],
  "Non-wood forest products": ["Bamboo culm", "Cork, raw", "Cork slab"],
  "Office equipment (excluding peripherals)": [
    "Used toner module, laser printer, colour",
    "Used toner module, laser printer, black/white",
  ],
  "Oleaginous fruits": ["Coconut, dehusked", "Olive", "Palm fruit bunch"],
  "Other animals": ["Cocoons"],
  "Other articles of paper and paperboard": ["Cellulose fibre"],
  "Other civil engineering projects": ["Chemical factory"],
  "Other electrical equipment": [
    "Anode, for metal electrolysis",
    "Anode, prebake, for aluminium electrolysis",
    "Charger, for electric scooter",
    "Anode, paste, for aluminium electrolysis",
    "Cathode, for aluminium electrolysis",
    "Charger, electric passenger car",
    "Inverter, for electric passenger car",
    "Aluminium collector foil, for li-ion battery",
    "Copper collector foil, for li-ion battery",
  ],
  "Other electronic and electric wires and cables": ["Cable, unspecified"],
  "Other non-ferrous metal ores": [
    "Magnesium oxide",
    "Sulfidic tailing, off-site, high gold content",
    "Lead concentrate",
    "Platinum group metal concentrate",
    "Tungsten concentrate",
    "Thulium oxide",
    "Ytterbium oxide",
    "Bulk lead-zinc concentrate",
    "Mischmetal",
    "Silver",
    "Tantalum concentrate, 30% ta2o5",
    "Cobalt carbonate",
    "Lanthanum-cerium oxide",
    "Electrolyte, copper-rich",
    "Cobalt hydroxide",
    "Gadolinium oxide",
    "Copper concentrate, sulfide ore",
    "Erbium oxide",
    "Stibnite concentrate",
    "Europium oxide",
    "Bauxite",
    "Dysprosium oxide",
    "Lutetium oxide",
    "Chromite ore concentrate",
    "Rare earth oxide concentrate, 70% reo",
    "Nickel sulfate",
    "Manganese concentrate",
    "Praseodymium-neodymium oxide",
    "Zircon",
    "Barite",
    "Yttrium oxide",
    "Lanthanum oxide",
    "Praseodymium oxide",
    "Tin concentrate",
    "Zinc concentrate",
    "Neodymium oxide",
    "Rare earth oxide concentrate, 50% reo",
    "Portachrom",
    "Holmium oxide",
    "Spodumene",
    "Rare earth carbonate concentrate",
    "Samarium-europium-gadolinium oxide",
    "Ilmenite, 54% titanium dioxide",
    "Terbium-dysprosium oxide",
    "Titania slag, 94% titanium dioxide",
    "Gold, unrefined",
    "Silver, unrefined",
    "Cerium oxide",
    "Cobalt oxide",
    "Mercury",
    "Molybdenite",
    "Strontium sulfate, 90% srso4",
    "Gold",
    "Pyrochlore concentrate",
    "Magnesium sulfate",
    "Terbium oxide",
    "Samarium oxide",
    "Cobalt acetate",
    "Titania slag, 85% titanium dioxide",
  ],
  "Other non-perennial crops": [
    "Grass, organic",
    "Alfalfa-grass mixture, swiss integrated production",
    "Alfalfa-grass silage",
    "Grass silage, swiss integrated production",
    "Hay, organic, intensive",
    "Maize silage",
    "Grass, swiss integrated production",
    "Hay, swiss integrated production, intensive",
    "Grass seed, swiss integrated production, at farm",
    "Hay, swiss integrated production, extensive",
    "Maize silage, swiss integrated production",
    "Maize silage, organic",
    "Coriander",
    "Clover seed, swiss integrated production, at farm",
    "Hay",
    "Fodder beet, swiss integrated production",
    "Grass silage, organic",
  ],
  "Other perennial crops": [
    "Wood chips and particles, willow",
    "Miscanthus, chopped",
  ],
  "Other porcelain and ceramic products": ["Ferrite"],
  "Other rubber products": ["Tube insulation, elastomere"],
  "Other tree and bush fruits and nuts": [
    "Strawberry",
    "Almond",
    "Kiwi",
    "Cashew",
  ],
  "Packaging activities": [
    "Packing, lime product",
    "Packing, cement",
    "Packing, fibre cement product",
    "Packing, clay product",
  ],
  "Paints, varnishes and ink": [
    "Coating powder",
    "Acrylic varnish, with water, in 53% solution state",
    "Alkyd paint, white, without solvent, in 60% solution state",
    "Magnetite",
    "Printing ink, rotogravure, without solvent, in 55% toluene solution state",
    "Acrylic binder, with water, in 54% solution state",
    "Acrylic dispersion, with water, in 58% solution state",
    "Alkyd paint, white, without water, in 60% solution state",
    "Toner, colour, powder",
    "Toner, black, powder",
    "Alkyd resin, long oil, without solvent, in 70% white spirit solution state",
    "Acrylic filler",
    "Printing ink, offset, without solvent, in 47.5% solution state",
    "Solvent for paint",
    "Electrostatic paint",
    "Solvent for chromatography analysis",
  ],
  "Parts and accessories for motor vehicles": [
    "Converter, for electric passenger car",
  ],
  Peat: ["Peat"],
  "Pesticides and other agrochemical products": [
    "Metolachlor",
    "Wood preservative, organic, outdoor use, no ground contact",
    "Mancozeb",
    "Phenoxy-compound",
    "Wood preservative, creosote",
    "Atrazine",
    "Mecoprop",
    "Prosulfocarb",
    "Chlorothalonil",
    "Pyrethroid-compound",
    "Wood preservative, inorganic salt, containing cr",
    "Nitrile-compound",
    "Wood preservative, water-based, indoor use, dry",
    "Pesticide, unspecified",
    "Benzo[thia]diazole-compound",
    "Pyridazine-compound",
    "Glyphosate",
    "Metamitron",
    "Dithiocarbamate-compound",
    "Bipyridylium-compound",
    "Wood preservative, water-based, indoor use, occasionally wet",
    "Chlorotoluron",
    "Diphenylether-compound",
    "Diazole-compound",
    "Triazine-compound, unspecified",
    "Pendimethalin",
    "Captan",
    "Wood preservative, organic salt, cr-free",
    "Cyclic n-compound",
    "Benzimidazole-compound",
    "Dinitroaniline-compound",
    "Organophosphorus-compound, unspecified",
    "[thio]carbamate-compound",
    "Diazine-compound",
    "Wood preservative, organic, indoor use, dry",
    "Benzoic-compound",
    "Folpet",
    "Wood preservative, organic, indoor use, occasionally wet",
    "Orbencarb",
    "Aclonifen",
    "Acetamide-anillide-compound, unspecified",
    "Wood preservative, water-based, outdoor use, no ground contact",
    "Phosphane",
    "Phthalimide-compound",
    "Pyridine-compound",
    "Dimethenamide",
    "[sulfonyl]urea-compound",
    "Fosetyl-al",
    "Isoproturon",
    "Napropamide",
    "Metaldehyde",
  ],
  "Pharmaceuticals, medicinal chemical and botanical products": [
    "Ascorbic acid",
  ],
  "Photocopying and document preparation": ["Printed paper"],
  "Plastics and synthetic rubber in primary forms": [
    "Vinyl chloride",
    "Nylon 6-6, glass-filled",
    "Synthetic rubber",
    "Polyethylene terephthalate, granulate, amorphous",
    "Polyvinylchloride, bulk polymerised",
    "Polyurethane, flexible foam, flame retardant",
    "Urea formaldehyde resin",
    "Bisphenol a epoxy based vinyl ester resin",
    "Nylon 6",
    "Toluene diisocyanate",
    "Polyester resin, unsaturated",
    "Latex",
    "Polyethylene terephthalate, granulate, bottle grade",
    "Polyphenylene sulfide",
    "Phenolic resin",
    "Ethylene vinyl acetate copolymer",
    "Polybutadiene",
    "Silicone product",
    "Polystyrene, high impact",
    "Purified terephthalic acid",
    "Polystyrene, general purpose",
    "Tetrafluoroethylene",
    "Polyol",
    "Polypropylene, granulate",
    "Polystyrene, expandable",
    "Polyurethane, flexible foam",
    "Polyvinylfluoride",
    "Polyurethane, rigid foam",
    "Polyvinylidenchloride, granulate",
    "Isophthalic acid based unsaturated polyester resin",
    "Styrene-acrylonitrile copolymer",
    "Polyvinylchloride, emulsion polymerised",
    "Polyethylene, linear low density, granulate",
    "Polyvinylchloride, suspension polymerised",
    "Methylene diphenyl diisocyanate",
    "Vinyl acetate",
    "Acrylonitrile-butadiene-styrene copolymer",
    "Cationic resin",
    "Polyethylene, low density, granulate",
    "Anionic resin",
    "Nylon 6, glass-filled",
    "Polycarbonate",
    "Polyethylene, high density, granulate",
    "Epoxy resin insulator, sio2",
    "Polyvinylfluoride, dispersion",
    "Dicyclopentadiene based unsaturated polyester resin",
    "Epoxy resin insulator, al2o3",
    "Nylon 6-6",
    "Melamine formaldehyde resin",
    "Orthophthalic acid based unsaturated polyester resin",
    "Polysulfide, sealing compound",
    "Polylactide, granulate",
    "Tetrafluoroethylene film, on glass",
    "Maleic unsaturated polyester resin",
    "Acetone cyanohydrin",
    "Methyl methacrylate",
    "Butadiene",
    "Polymethyl methacrylate, beads",
    "Polystyrene, extruded",
  ],
  "Plastics products": [
    "Calendering, rigid sheets",
    "Packaging, for fertilisers",
    "Thermoforming, with calendering",
    "Urea formaldehyde foam slab, hard",
    "Injection moulding",
    "Ethylvinylacetate, foil",
    "Extrusion of plastic sheets and thermoforming, inline",
    "Polystyrene foam slab for perimeter insulation",
    "Stretch blow moulding",
    "Extrusion, plastic pipes",
    "Packaging, for pesticides",
    "Carbon fibre reinforced plastic, injection moulded",
    "Blow moulding",
    "Extrusion, co-extrusion",
    "Glass fibre reinforced plastic, polyamide, injection moulded",
    "Packaging, for fertilisers or pesticides",
    "Polystyrene foam slab, 10% recycled",
    "Polyvinylfluoride, film",
    "Polystyrene foam slab with graphite, 6% recycled",
    "Polystyrene foam slab",
    "Polystyrene scrap, post-consumer",
    "Glass fibre reinforced plastic, polyester resin, hand lay-up",
    "Polymethyl methacrylate, sheet",
    "Packaging film, low density polyethylene",
    "Extrusion, plastic film",
    "Thermoforming of plastic sheets",
    "Urea formaldehyde foam, in situ foaming",
    "Polymer foaming",
  ],
  "Pome fruits and stone fruits": [
    "Apple",
    "Peach",
    "Pomegranate",
    "Apricot",
    "Pear",
  ],
  "Post-harvest crop activities": [
    "Potato grading",
    "Mango, conditioned",
    "Cottonseed, organic",
    "Cottonseed",
    "Fibre, cotton, organic",
    "Operation, dried roughage store, air dried, solar",
    "Operation, dried roughage store, cold-air dried, conventional",
    "Fibre, cotton",
    "Operation, dried roughage store, non ventilated",
  ],
  Poultry: ["Chicken for slaughtering, live weight"],
  "Prepared animal feeds": [
    "Barley grain, feed",
    "Rye grain, feed, swiss integrated production",
    "Tilapia feed, 24-28% protein",
    "Wheat grain, feed",
    "Wheat grain, feed, swiss integrated production",
    "Wheat grain, feed, organic",
    "Mineral supplement, for beef cattle",
    "Maize grain, feed, swiss integrated production",
    "Maize grain, feed",
    "Protein pea, feed, swiss integrated production",
    "Soybean, feed",
    "Fava bean, feed, swiss integrated production",
    "Barley grain, feed, swiss integrated production",
    "Barley grain, feed, organic",
    "Protein feed, 100% crude",
    "Oat grain, feed",
    "Trout feed, 42% protein",
    "Rye grain, feed, organic",
    "Maize grain, feed, organic",
  ],
  "Prepared meals and dishes": ["Frozen fish sticks, hake"],
  Printing: ["Printed paper, offset"],
  "Products of wood, cork, straw and plaiting materials": [
    "Bamboo pole",
    "Woven bamboo mat",
    "Flattened bamboo",
  ],
  "Pulp, paper and paperboard": [
    "Turpentine",
    "Paper, woodfree, uncoated",
    "Sulfite pulp, bleached",
    "Stone groundwood pulp",
    "Folding boxboard carton",
    "Paper, newsprint",
    "Kraft paper",
    "Graphic paper, 100% recycled",
    "Chemi-thermomechanical pulp",
    "Paper, woodfree, coated",
    "Core board",
    "Thermo-mechanical pulp",
    "Paper, woodcontaining, supercalendered",
    "Tissue paper",
    "Sulfate pulp, unbleached",
    "Solid bleached and unbleached board carton",
    "White lined chipboard carton",
    "Tall oil, crude",
    "Sulfate pulp, bleached",
    "Paper, woodcontaining, lightweight coated",
    "Deinked pulp, wet lap",
  ],
  "Refined petroleum products": [
    "Hydrogen, gaseous",
    "Propylene",
    "C3 hydrocarbon mixture",
    "Propylene, pipeline system",
    "Diesel",
    "Pitch",
    "Methylcyclopentane",
    "Petrol, 5% ethanol by volume from biomass",
    "Base oil",
    "Fatty acid methyl ester",
    "Refinery gas",
    "2-methylpentane",
    "Paraffin",
    "Wax, lost-wax casting",
    "Hydrogen, liquid",
    "Petrol, unleaded",
    "Hexane",
    "Liquefied petroleum gas",
    "White spirit",
    "Ethylene, pipeline system",
    "Petrol, 4% etbe additive by volume, with ethanol from biomass",
    "Petrol, two-stroke blend",
    "Diesel, low-sulfur",
    "Fraction 1 from naphtha separation",
    "Heptane",
    "Fraction 7 from naphtha separation",
    "Benzene",
    "Kerosene",
    "Fraction 8 from naphtha separation",
    "Lubricating oil",
    "1,1-dimethylcyclopentane",
    "Petrol, 15% etbe additive by volume, with ethanol from biomass",
    "Heavy fuel oil",
    "Naphtha",
    "2,3-dimethylbutan",
    "Butene, mixed",
    "Petroleum coke",
    "Ethylene",
    "Petrol, low-sulfur",
    "Petroleum slack wax",
    "Light fuel oil",
    "Reformate",
  ],
  "Refractory products": [
    "Refractory, fireclay, packed",
    "Refractory material, acid",
    "Silicon carbide",
    "Refractory, basic, packed",
    "Refractory, high aluminium oxide, packed",
  ],
  Rice: ["Rice, non-basmati", "Rice, basmati"],
  Salt: ["Salt", "Sodium chloride, powder", "Sodium chloride, brine solution"],
  "Seed processing for propagation": [
    "Maize seed, for sowing",
    "Soybean seed, for sowing",
    "Rye seed, for sowing",
    "Peanut seed, for sowing",
    "Pea seed, organic, for sowing",
    "Maize seed, organic, for sowing",
    "Barley seed, for sowing",
    "Red kidney bean seed, for sowing",
    "Navy bean seed, for sowing",
    "Potato seed, for setting",
    "Rice seed, for sowing",
    "Clover seed, swiss integrated production, for sowing",
    "Barley seed, organic, for sowing",
    "Rape seed, organic, for sowing",
    "Rye seed, organic, for sowing",
    "Potato seed, organic, for setting",
    "Sunflower seed, for sowing",
    "Fava bean seed, organic, for sowing",
    "Potato seed, swiss integrated production, for setting",
    "Wheat seed, for sowing",
    "Carrot seed, for sowing",
    "Sugar beet seed, for sowing",
    "Grass seed, organic, for sowing",
    "Soybean seed, organic, for sowing",
    "Lentil seed, for sowing",
    "Barley seed, swiss integrated production, for sowing",
    "Cottonseed, organic, for sowing",
    "Linseed seed, for sowing",
    "Oat seed, for sowing",
    "Cottonseed, for sowing",
    "Maize seed, swiss integrated production, for sowing",
    "Pinto bean seed, for sowing",
    "Pea seed, for sowing",
    "Fodder beet seed, for sowing",
    "Beet seed, swiss integrated production, for sowing",
    "Grass seed, swiss integrated production, for sowing",
    "Wheat seed, swiss integrated production, for sowing",
    "Wheat seed, organic, for sowing",
    "Rye seed, swiss integrated production, for sowing",
    "Rape seed, for sowing",
    "Fava bean seed, for sowing",
  ],
  "Sheep and goats": [
    "Sheep fleece in the grease",
    "Sheep for slaughtering, live weight",
  ],
  "Silviculture and other forestry activities": [
    "Land tenure, arable land, measured as carbon net primary productivity, forest, intensive",
  ],
  "Site preparation": ["Blasting"],
  "Soap and detergents": [
    "Tallow, unrefined",
    "Alkyl sulphate (c12-14)",
    "Foaming agent",
    "Layered sodium silicate, sks-6, powder",
    "Ethoxylated alcohol (ae>20)",
    "Non-ionic surfactant",
    "Polycarboxylates, 40% active substance",
    "Cocamide diethanolamine",
    "Sodium perborate, tetrahydrate, powder",
    "Ethoxylated alcohol (ae3)",
    "Esterquat",
    "Sodium metasilicate pentahydrate, 58% active substance, powder",
    "Alkylbenzene, linear",
    "Ethoxylated alcohol (ae7)",
    "Sodium perborate, monohydrate, powder",
    "Zeolite, slurry, without water, in 50% solution state",
    "Sodium percarbonate, powder",
    "Soap",
    "Zeolite, powder",
    "Alkylbenzene sulfonate, linear, petrochemical",
    "Fatty alcohol sulfate",
    "Amine oxide",
    "Sodium tripolyphosphate",
    "Ethoxylated alcohol (ae11)",
    "Cleaning consumables, without water, in 13.6% solution state",
  ],
  "Solid, liquid and gaseous fuels and related products": ["Petroleum"],
  "Spices, aromatic, drug and pharmaceutical crops": [
    "Vanilla",
    "Bell pepper",
    "Mint",
    "Chilli",
  ],
  "Starches and starch products": [
    "Maize starch",
    "Polyester-complexed starch biopolymer",
    "Glucose",
    "Potato starch",
  ],
  "Steam and air conditioning supply": ["Steam, in chemical industry"],
  Stone: [
    "Natural stone plate, polished",
    "Natural stone plate, cut",
    "Natural stone plate, grounded",
  ],
  "Stone, sand and clay": [
    "Clay",
    "Feldspar",
    "Limestone, crushed, washed",
    "Sand",
    "Lime",
    "Calcareous marl",
    "Basalt",
    "Bentonite",
    "Pumice",
    "Anhydrite rock",
    "Malusil",
    "Shale",
    "Limestone, crushed, for mill",
    "Steatite",
    "Limestone, unprocessed",
    "Gravel, crushed",
    "Perlite",
    "Gypsum, mineral",
    "Lime, packed",
    "Silica sand",
    "Vermiculite",
    "Kaolin",
    "Gravel, round",
    "Laterite, mineral",
  ],
  Sugar: [
    "Bagasse, from sugarcane",
    "Sugar, from sugarcane",
    "Molasses, from sugar beet",
    "Ethanol, without water, in 95% solution state, from fermentation",
    "Sugar beet pulp",
    "Sugar, from sugar beet",
  ],
  "Sugar cane": ["Sugarcane"],
  "Support activities for animal production": [
    "Land tenure, arable land, measured as carbon net primary productivity, pasture, man made",
    "Milking",
  ],
  "Support activities for crop production": [
    "Phacelia silage",
    "Inorganic phosphorus fertiliser, as p2o5",
    "Organo-mineral nitrogen fertiliser, as n",
    "Ryegrass-red&egyptian clover-mixture silage",
    "Manure, liquid, swine",
    "Filter cake, from sugarcane juice filtration",
    "Vinasse, from fermentation of sugar beet molasses",
    "Organo-mineral phosphorus fertiliser, as p2o5",
    "Poultry manure, fresh",
    "Inorganic nitrogen fertiliser, as n",
    "Ash, from combustion of straw",
    "Vinasse, from fermentation of sugar beet",
    "Vinasse, from fermentation of sweet sorghum",
    "Manure, solid, cattle",
    "Land tenure, arable land, measured as carbon net primary productivity, annual crop",
    "Vinasse, from fermentation of sugarcane",
    "Manure, liquid, cattle",
    "Organic nitrogen fertiliser, as n",
    "Ryegrass silage",
    "Glycerin distillate bottom",
    "Potassium chloride sludge",
    "Ash, from combustion of bagasse from sugarcane",
    "Organic phosphorus fertiliser, as p2o5",
    "Coconut husk",
    "Ryegrass-egyptian&persian clover-mixture silage",
    "Inorganic potassium fertiliser, as k2o",
    "Land tenure, arable land, measured as carbon net primary productivity, perennial crop",
    "Sunflower silage",
    "Organic potassium fertiliser, as k2o",
    "Solid manure loading and spreading, by hydraulic loader and spreader",
    "Fermentation filtrate",
    "Organo-mineral potassium fertiliser, as k2o",
  ],
  "Swine/pigs": ["Swine for slaughtering, live weight"],
  "Textile and fur products": ["Washing, drying and finishing laundry"],
  "Textile fibres": [
    "Reeled raw silk hank",
    "Yarn, cotton",
    "Stalk",
    "Textile, nonwoven polypropylene",
    "Fibre, kenaf",
    "Yarn, jute",
    "Yarn, silk",
    "Fibre, flax",
    "Fibre, jute",
    "Yarn, kenaf",
    "Flax husks",
    "Textile, nonwoven polyester",
    "Fibre, silk, short",
  ],
  Textiles: [
    "Bleaching, textile",
    "Textile, woven cotton",
    "Batch dyeing, fibre, cotton",
    "Fleece, polyethylene",
    "Bleaching and dyeing, yarn",
    "Mercerizing, textile",
    "Sanforizing, textile",
    "Textile, jute",
    "Continuous dyeing, fibre, cotton",
    "Textile, silk",
    "Weaving, synthetic fibre",
    "Finishing, textile, woven cotton",
    "Finishing, textile, knit cotton",
    "Textile, kenaf",
    "Polar fleece, energy use only",
  ],
  "Tropical and subtropical fruits": [
    "Palm date, organic",
    "Pineapple",
    "Banana",
    "Palm date",
    "Mango",
    "Avocado",
    "Papaya",
  ],
  "Uranium and thorium ores": ["Uranium, in yellowcake", "Uranium ore, as u"],
  "Utility projects": ["Used nitrate salts, for solar power application"],
  "Vegetable and animal oils and fats": [
    "Rape meal",
    "Palm oil, crude",
    "Cottonseed meal",
    "Rape oil, crude",
    "Soybean meal",
    "Palm oil, refined",
    "Palm kernel oil, crude",
    "Cottonseed oil, crude",
    "Palm kernel meal",
    "Soybean oil, crude",
    "Vegetable oil, refined",
    "Soybean oil, refined",
    "Cottonseed oil, refined",
    "Coconut oil, crude",
  ],
  "Vegetables and melons, roots and tubers": [
    "Spinach",
    "Tomato, fresh grade",
    "Potato seed, swiss integrated production, at farm",
    "Aubergine",
    "Potato",
    "Fennel",
    "Cauliflower",
    "Potato, swiss integrated production",
    "Onion",
    "Cabbage white",
    "Potato, organic",
    "Radish",
    "Tomato, processing grade",
    "Cucumber",
    "Green asparagus",
    "Celery",
    "Cabbage red",
    "Sugar beet",
    "Carrot",
    "Iceberg lettuce",
    "Potato seed, at farm",
    "Carrot seed, swiss integrated production, at farm",
    "Paris market carrot",
    "Melon",
    "Broccoli",
    "White asparagus",
    "Zucchini",
    "Lettuce",
    "Potato seed, organic, at farm",
  ],
  "Veneer sheets and wood-based panels": [
    "Wood chips, dry, measured as dry mass",
    "Paper, melamine impregnated",
  ],
  "Water collection, treatment and supply": [
    "Water, deionised",
    "Water, completely softened",
    "Tap water",
    "Water, harvested from rainwater",
    "Water, decarbonised",
    "Water, ultrapure",
  ],
  Wood: [
    "Shavings, hardwood, measured as dry mass",
    "Wood preservation, spray tunnel/deluging, water-based, indoor use, dry",
    "Shavings, softwood, loose, measured as dry mass",
    "Shavings, softwood, measured as dry mass",
    "Wood preservation, vacuum pressure method, organic salts, cr-free, outdoor use, ground contact",
    "Wood preservation, vacuum pressure method, inorganic salt, containing cr, outdoor use, ground contact",
    "Wood pellet, measured as dry mass",
    "Bark chips, wet, measured as dry mass",
    "Wood preservation, spray tunnel/deluging, organic solvent-based, indoor use, dry",
    "Wood preservation, dipping/immersion method, organic solvent-based, outdoor use, no ground contact",
    "Wood preservation, dipping/immersion method, organic solvent-based, indoor use, dry",
    "Wood preservation, dipping/immersion method, water-based, indoor use, dry",
    "Wood preservation, hot/cold dipping, creosote, outdoor use, ground contact",
    "Slab and siding, hardwood, wet, measured as dry mass",
    "Wood preservation, pressure vessel, creosote, outdoor use, ground contact",
    "Sawdust, wet, measured as dry mass",
    "Wood preservation, spray tunnel/deluging, water-based, outdoor use, no ground contact",
    "Wood preservation, oscillating pressure method, inorganic salt, containing cr, outdoor use, ground contact",
    "Wood wool",
    "Wood preservation, spray tunnel/deluging, water-based, indoor use, occasionally wet",
    "Slab and siding, softwood, wet, measured as dry mass",
    "Wood preservation, dipping/immersion method, water-based, outdoor use, no ground contact",
    "Wood preservation, spray tunnel/deluging, organic solvent-based, outdoor use, no ground contact",
    "Sawdust, loose, wet, measured as dry mass",
    "Wood preservation, dipping/immersion method, water-based, indoor use, occasionally wet",
    "Wood preservation, oscillating pressure method, organic salt, cr-free, outdoor use, ground contact",
    "Wood preservation, dipping/immersion method, organic solvent-based, indoor use, occasionally wet",
    "Wood chipping, industrial residual wood, stationary electric chipper",
    "Bark",
    "Shavings, hardwood, loose, measured as dry mass",
    "Wood preservation, spray tunnel/deluging, organic solvent-based, indoor use, occasionally wet",
  ],
} as Record<string, Array<string>>
